ls:
    resources/js/store:
        .ts: pascalcase
    "*":
        .js: camelcase
        .ts: camelcase
        .vue: pascalcase
        .dir: snakecase
        .type.ts: camelcase
ignore:
    - node_modules
    - vendor
    - public/build
    - public/tinymce
