name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "@daily"
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:43.2.4
    steps:
      - uses: actions/checkout@v4

      - run: renovate
        working-directory: ${{ gitea.workspace }}
        env:
          RENOVATE_CONFIG_FILE: "renovate-config.json"
          LOG_LEVEL: "info"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        