name: SAST

on:
#  push:
#  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Semgrep
        run: semgrep scan --config p/php

  phpstan:
    runs-on: ubuntu-latest
    container:
      image: git.stemmechanics.com.au/stemmechanics/laravel-ci:php8.4-node24

    steps:
      - uses: actions/checkout@v6

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: composer-${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install PHP Dependencies
        env:
          COMPOSER_CACHE_DIR: /tmp/composer-cache
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G