<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\Account\ClassroomController as AccountClassroomController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BasController;
use App\Http\Controllers\ChildAccountController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\Account\ConnectedAppController;
use App\Http\Controllers\ClassHelpRequestController;
use App\Http\Controllers\ClassroomController;
use App\Http\Controllers\CustomPageController;
use App\Http\Controllers\Admin\OAuthClientController;
use App\Http\Controllers\Admin\ClassroomController as AdminClassroomController;
use App\Http\Controllers\EmailSubscriptionController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\FinanceFileController;
use App\Http\Controllers\ForumCategoryController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\ForumModerationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ClassroomChatController;
use App\Http\Controllers\ClassroomClientErrorController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\LiveKitTokenController;
use App\Http\Controllers\LiveKitWebhookController;
use App\Http\Controllers\MinecraftController;
use App\Http\Controllers\MinecraftWebhookController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PickListTemplateController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\QuoteController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\ServerController;
use App\Http\Controllers\ShopAdminOrderController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ShopCouponController;
use App\Http\Controllers\ShopProductController;
use App\Http\Controllers\ShopSettingsController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SiteOptionController;
use App\Http\Controllers\OpenId\UserInfoController;
use App\Http\Controllers\SquareWebhookController;
use App\Http\Controllers\StemcraftController;
use App\Http\Controllers\StoreOrderController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TaxAdjustmentController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WorkshopController;
use App\Http\Controllers\WorkshopPickListController;
use App\Http\Controllers\WorkshopTicketFlowController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/sitemap.xml', [SitemapController::class, 'index'])->name('sitemap.xml');

// Route::get('posts', [PostController::class, 'index'])->name('post.index');
// Route::get('posts/{post}', [PostController::class, 'show'])->name('post.show');
Route::get('workshops', [WorkshopController::class, 'index'])->name('workshop.index');
Route::get('workshops/past', [WorkshopController::class, 'past_index'])->name('workshop.past.index');
Route::get('workshops/{workshop}', [WorkshopController::class, 'show'])->name('workshop.show');
Route::post('workshops/{workshop}/private-access', [WorkshopController::class, 'privateAccess'])->name('workshop.private-access');
Route::post('workshops/{workshop}/interest', [WorkshopController::class, 'interest'])->name('workshop.interest');
Route::get('workshops/{workshop}/tickets', [WorkshopTicketFlowController::class, 'start'])->name('workshop.ticket.flow.start');
Route::get('workshops/{workshop}/tickets/login', [WorkshopTicketFlowController::class, 'loginRedirect'])->name('workshop.ticket.flow.login');
Route::post('workshops/{workshop}/tickets/start', [WorkshopTicketFlowController::class, 'begin'])->name('workshop.ticket.flow.begin');
Route::get('workshops/{workshop}/tickets/payment', [WorkshopTicketFlowController::class, 'payment'])->name('workshop.ticket.flow.payment');
Route::post('workshops/{workshop}/tickets/payment', [WorkshopTicketFlowController::class, 'processPayment'])->name('workshop.ticket.flow.payment.process');
Route::get('workshops/{workshop}/tickets/details', [WorkshopTicketFlowController::class, 'details'])->name('workshop.ticket.flow.details');
Route::get('workshops/{workshop}/tickets/details/keepalive', [WorkshopTicketFlowController::class, 'detailsKeepAlive'])->name('workshop.ticket.flow.details.keepalive');
Route::post('workshops/{workshop}/tickets/details', [WorkshopTicketFlowController::class, 'saveDetails'])->name('workshop.ticket.flow.details.save');
Route::get('workshops/{workshop}/tickets/complete', [WorkshopTicketFlowController::class, 'complete'])->name('workshop.ticket.flow.complete');
Route::get('workshops/{workshop}/tickets/complete/download-all', [WorkshopTicketFlowController::class, 'downloadAll'])->name('workshop.ticket.flow.complete.download-all');
Route::post('workshops/{workshop}/tickets/cancel', [WorkshopTicketFlowController::class, 'cancel'])->name('workshop.ticket.flow.cancel');

Route::middleware('shop.public')->group(function () {
    Route::get('/store', [ShopController::class, 'index'])->name('shop.index');
    Route::get('/store/cart', [ShopController::class, 'cart'])->name('shop.cart.show');
    Route::post('/store/cart/update', [ShopController::class, 'updateCart'])->name('shop.cart.update');
    Route::post('/store/cart/preferences', [ShopController::class, 'updateCartPreferences'])->name('shop.cart.preferences');
    Route::post('/store/cart/remove', [ShopController::class, 'removeFromCart'])->name('shop.cart.remove');
    Route::post('/store/cart/coupon', [ShopController::class, 'applyCoupon'])->name('shop.cart.coupon.apply');
    Route::post('/store/cart/coupon/remove', [ShopController::class, 'removeCoupon'])->name('shop.cart.coupon.remove');
    Route::post('/store/cart/{product}', [ShopController::class, 'addToCart'])->name('shop.cart.add');
    Route::middleware('full-account')->group(function () {
        Route::get('/store/checkout', [ShopController::class, 'checkout'])->name('shop.checkout');
        Route::post('/store/checkout', [ShopController::class, 'placeOrder'])->name('shop.checkout.place-order');
        Route::get('/store/checkout/payment', [ShopController::class, 'checkoutPayment'])->name('shop.checkout.payment');
        Route::post('/store/checkout/payment', [ShopController::class, 'processCheckoutPayment'])->name('shop.checkout.payment.process');
    });
    Route::get('/store/quote-requested', [ShopController::class, 'quoteRequested'])->name('shop.quote.requested');
    Route::get('/store/{product}', [ShopController::class, 'show'])->name('shop.product.show');
});

Route::get('/tracking/{accessToken}', [StoreOrderController::class, 'trackingShow'])->name('shop.order.tracking');
Route::post('/tracking/{accessToken}/pay', [StoreOrderController::class, 'trackingPay'])->name('shop.order.tracking.pay');
Route::get('/tracking/{accessToken}/downloads/{storeOrderItemDownload}', [StoreOrderController::class, 'trackingDownload'])->name('shop.order.tracking.download');
Route::post('/tracking/{accessToken}/downloads/{storeOrderItemDownload}/verify', [StoreOrderController::class, 'trackingVerifyDownload'])->name('shop.order.tracking.download.verify');

Route::redirect('/shop', '/store', 302);
Route::redirect('/shop/{path}', '/store/{path}', 302)->where('path', '.*');

Route::get('search', [SearchController::class, 'index'])->name('search.index');
Route::get('/stemcraft', [StemcraftController::class, 'index'])->name('stemcraft.index');
Route::get('/stemcraft/join', [StemcraftController::class, 'join'])->name('stemcraft.join');
Route::get('/stemcraft/rules', [StemcraftController::class, 'rules'])->name('stemcraft.rules');
Route::get('/stemcraft/faqs', [StemcraftController::class, 'faqs'])->name('stemcraft.faqs');
Route::get('/stemcraft/leaderboards', [StemcraftController::class, 'stats'])->name('stemcraft.leaderboards');
Route::get('/stemcraft/punishments', [StemcraftController::class, 'punishments'])->name('stemcraft.punishments');
Route::match(['GET', 'POST'], 'unsubscribe/discussions/{email}', [SubscribeController::class, 'destroyDiscussionNotifications'])->name('unsubscribe.discussions');
Route::match(['GET', 'POST'], 'unsubscribe/{email}', [SubscribeController::class, 'destroy'])->name('unsubscribe');
Route::get('/tickets', [TicketController::class, 'showRequest'])->name('tickets.request');
Route::post('/tickets', [TicketController::class, 'sendMagicLink'])->middleware('throttle:magic-link')->name('tickets.send');
Route::get('/tickets/magic', [TicketController::class, 'showByMagicToken'])->name('tickets.magic');
Route::get('/tickets/{ticket}/pdf', [TicketController::class, 'pdf'])->name('tickets.pdf');
Route::post('/tickets/{ticket}/attendee', [TicketController::class, 'updateAttendee'])->name('tickets.attendee.update');
Route::get('/tickets/{ticket}/invoice/pdf', [TicketController::class, 'invoicePdf'])->name('tickets.invoice.pdf');
Route::get('/tickets/{ticket}/invoice/receipts', [TicketController::class, 'invoiceReceipts'])->name('tickets.invoice.receipts');
Route::get('/tickets/{ticket}/invoice/receipts/{payment}/pdf', [TicketController::class, 'invoiceReceiptPdf'])->name('tickets.invoice.receipt.pdf');
Route::post('/tickets/{ticket}/cancel', [TicketController::class, 'cancel'])->name('tickets.cancel');
Route::get('/invoices/magic', [InvoiceController::class, 'showByMagicToken'])->name('invoice.magic');
Route::get('/invoices/{invoice}/pdf', [InvoiceController::class, 'magicPdf'])->name('invoice.magic.pdf');
Route::post('/invoices/{invoice}/pay', [InvoiceController::class, 'magicPay'])->name('invoice.magic.pay');
Route::get('/quotes/{quote}/review', [QuoteController::class, 'showByMagicLink'])->middleware('signed')->name('quote.magic.show');
Route::post('/quotes/{quote}/review/accept', [QuoteController::class, 'acceptByMagicLink'])->middleware('signed')->name('quote.magic.accept');
Route::post('/quotes/{quote}/review/cancel', [QuoteController::class, 'cancelByMagicLink'])->middleware('signed')->name('quote.magic.cancel');
Route::get('/invoices/{invoice}/receipts/{payment}/pdf', [InvoiceController::class, 'receiptPdf'])->middleware('signed')->name('invoice.receipt.pdf');
Route::get('/pay/{invoice}', [InvoiceController::class, 'publicPayShow'])->name('invoice.public.pay.show');
Route::post('/pay/{invoice}', [InvoiceController::class, 'publicPayProcess'])->middleware('throttle:invoice-public')->name('invoice.public.pay.process');
Route::post('/pay/{invoice}/email-documents', [InvoiceController::class, 'publicEmailDocuments'])->middleware('throttle:invoice-public')->name('invoice.public.email-documents');
    Route::post('/webhooks/square', [SquareWebhookController::class, 'handle'])->name('webhook.square');
    Route::post('/webhooks/stemcraft/server', [MinecraftWebhookController::class, 'handle'])->name('webhook.stemcraft.server');
    Route::post('/webhooks/minecraft/server', [MinecraftWebhookController::class, 'handle'])->name('webhook.minecraft.server');
    Route::post('/webhooks/livekit', [LiveKitWebhookController::class, 'handle'])->name('webhook.livekit');
    Route::get('/link-options', [CustomPageController::class, 'linkOptions'])->name('custom-page.link-options');

Route::middleware('nocache')->group(function () {
    Route::get('/forum', [ForumController::class, 'index'])->name('forum.index');
    Route::get('/forum/snapshot', [ForumController::class, 'indexSnapshot'])->name('forum.index.snapshot');
    Route::get('/forum/{categorySlug}', [ForumController::class, 'showCategory'])->name('forum.category.show');
    Route::get('/forum/{categorySlug}/snapshot', [ForumController::class, 'categorySnapshot'])->name('forum.category.snapshot');
});

Route::middleware('auth')->group(function () {
    Route::get('/forum/notifications/summary', [ForumController::class, 'unreadSummary'])->middleware('nocache')->name('forum.notifications.summary');
    Route::get('/forum/{categorySlug}/create', [ForumController::class, 'createTopic'])->middleware('nocache')->name('forum.topic.create');
    Route::post('/forum/{categorySlug}/{topicSlug}/notifications', [ForumController::class, 'toggleNotifications'])->name('forum.topic.notifications');
    Route::post('/media', [MediaController::class, 'store'])->name('media.store');
    Route::get('/account', [AccountController::class, 'show'])->name('account.show');
    Route::post('/account', [AccountController::class, 'update'])->name('account.update');
    Route::post('/account/password', [AccountController::class, 'updatePassword'])->name('account.password.update');
    Route::post('/account/discussions/unsubscribe-all', [AccountController::class, 'unsubscribeAllDiscussionNotifications'])->name('account.discussions.unsubscribe-all');
    Route::delete('/account', [AccountController::class, 'destroy'])->name('account.destroy');
    Route::get('/account/classrooms', [AccountClassroomController::class, 'index'])->name('account.classrooms.index');
    Route::get('/account/connected-apps', [ConnectedAppController::class, 'index'])->name('account.oauth-apps.index');
    Route::delete('/account/connected-apps', [ConnectedAppController::class, 'destroyAll'])->name('account.oauth-apps.destroy-all');
    Route::delete('/account/connected-apps/{client}', [ConnectedAppController::class, 'destroy'])->name('account.oauth-apps.destroy');
    Route::get('/account/media', [MediaController::class, 'account_index'])->name('account.media.index');
    Route::delete('/account/media/{media}', [MediaController::class, 'account_destroy'])->name('account.media.destroy');
    Route::delete('/account/devices/{token}', [AccountController::class, 'destroyRememberedDevice'])->name('account.device.destroy');
    Route::patch('/account/devices/{token}/nickname', [AccountController::class, 'updateRememberedDeviceNickname'])->name('account.device.nickname.update');
    Route::get('/account/children', [ChildAccountController::class, 'index'])->name('account.children.index');
    Route::get('/account/children/create', [ChildAccountController::class, 'create'])->name('account.children.create');
    Route::get('/account/children/approvals', [ChildAccountController::class, 'approvals'])->name('account.children.approvals');
    Route::post('/account/children/approvals/bulk', [ChildAccountController::class, 'bulkUpdateApprovals'])->name('account.children.approvals.bulk');
    Route::post('/account/children', [ChildAccountController::class, 'store'])->name('account.children.store');
    Route::get('/account/children/{child}', [ChildAccountController::class, 'edit'])->name('account.children.edit');
    Route::put('/account/children/{child}', [ChildAccountController::class, 'update'])->name('account.children.update');
    Route::delete('/account/children/{child}', [ChildAccountController::class, 'destroy'])->name('account.children.destroy');
    Route::get('/account/children/{child}/forum-topics/{forumTopic}/approve-link', [ChildAccountController::class, 'approveTopicFromEmail'])->middleware('signed')->name('account.children.topic.approve-link');
    Route::post('/account/children/{child}/forum-topics/{forumTopic}/approve', [ChildAccountController::class, 'approveTopic'])->name('account.children.topic.approve');
    Route::post('/account/children/{child}/forum-topics/{forumTopic}/reject', [ChildAccountController::class, 'rejectTopic'])->name('account.children.topic.reject');
    Route::get('/account/children/{child}/forum-posts/{forumPost}/approve-link', [ChildAccountController::class, 'approvePostFromEmail'])->middleware('signed')->name('account.children.post.approve-link');
    Route::post('/account/children/{child}/forum-posts/{forumPost}/approve', [ChildAccountController::class, 'approvePost'])->name('account.children.post.approve');
    Route::post('/account/children/{child}/forum-posts/{forumPost}/reject', [ChildAccountController::class, 'rejectPost'])->name('account.children.post.reject');
    Route::get('/account/stemcraft', [MinecraftController::class, 'accountIndex'])->name('account.stemcraft.index');
    Route::patch('/account/stemcraft/accounts/{minecraftAccount}/owner', [MinecraftController::class, 'accountUpdateOwner'])->name('account.stemcraft.owner.update');
    Route::get('/class/{classSession}', [ClassroomController::class, 'show'])->name('class.show');
    Route::get('/class/{classSession}/help-requests', [ClassHelpRequestController::class, 'index'])->name('class.help-requests.index');
    Route::post('/class/{classSession}/help-request', [ClassHelpRequestController::class, 'store'])->name('class.help-requests.store');
    Route::post('/class/{classSession}/help-request/{helpRequest}/approve', [ClassHelpRequestController::class, 'approve'])->name('class.help-requests.approve');
    Route::post('/class/{classSession}/help-request/{helpRequest}/revoke', [ClassHelpRequestController::class, 'revoke'])->name('class.help-requests.revoke');
    Route::post('/class/{classSession}/chat', [ClassroomChatController::class, 'store'])->name('class.chat.store');
    Route::post('/class/{classSession}/client-error', [ClassroomClientErrorController::class, 'store'])->name('class.client-error.store');
    Route::post('/api/livekit/token', [LiveKitTokenController::class, 'store'])->name('livekit.token');

    Route::middleware('full-account')->group(function () {
        Route::get('/account/invoices', [InvoiceController::class, 'accountIndex'])->name('account.invoice.index');
        Route::get('/account/invoices/{invoice}', [InvoiceController::class, 'accountShow'])->name('account.invoice.show');
        Route::get('/account/invoices/{invoice}/receipts', [InvoiceController::class, 'accountReceipts'])->name('account.invoice.receipts');
        Route::get('/account/invoices/{invoice}/receipts/{payment}', [InvoiceController::class, 'accountReceiptShow'])->name('account.invoice.receipt.show');
        Route::post('/account/invoices/{invoice}/pay', [InvoiceController::class, 'accountPay'])->name('account.invoice.pay');
        Route::get('/account/invoices/{invoice}/pdf', [InvoiceController::class, 'accountPdf'])->name('account.invoice.pdf');
        Route::get('/account/invoices/{invoice}/receipts/{payment}/pdf', [InvoiceController::class, 'accountReceiptPdf'])->name('account.invoice.receipt.pdf');
        Route::get('/account/quotes', [QuoteController::class, 'accountIndex'])->name('account.quote.index');
        Route::get('/account/quotes/{quote}', [QuoteController::class, 'accountShow'])->name('account.quote.show');
        Route::post('/account/quotes/{quote}/accept', [QuoteController::class, 'accountAccept'])->name('account.quote.accept');
        Route::post('/account/quotes/{quote}/cancel', [QuoteController::class, 'accountCancel'])->name('account.quote.cancel');
        Route::get('/account/quotes/{quote}/pdf', [QuoteController::class, 'accountPdf'])->name('account.quote.pdf');
        Route::get('/account/tickets', [TicketController::class, 'accountIndex'])->name('account.ticket.index');
        Route::get('/account/tickets/{ticket}/pdf', [TicketController::class, 'accountPdf'])->name('account.ticket.pdf');
        Route::post('/account/tickets/{ticket}/attendee', [TicketController::class, 'updateAttendee'])->name('account.ticket.attendee.update');
        Route::get('/account/tickets/{ticket}/invoice/pdf', [TicketController::class, 'accountInvoicePdf'])->name('account.ticket.invoice.pdf');
        Route::post('/account/tickets/{ticket}/cancel', [TicketController::class, 'accountCancel'])->name('account.ticket.cancel');
        Route::get('/account/payments', [PaymentController::class, 'accountIndex'])->name('account.payment.index');
        Route::get('/account/payments/{payment}/receipt', [PaymentController::class, 'accountReceiptPdf'])->name('account.payment.receipt');
        Route::get('/account/orders', [StoreOrderController::class, 'accountIndex'])->name('account.order.index');
        Route::get('/account/orders/{storeOrder}', [StoreOrderController::class, 'accountShow'])->name('account.order.show');
        Route::post('/account/orders/{storeOrder}/pay', [StoreOrderController::class, 'accountPay'])->name('account.order.pay');
        Route::get('/account/orders/{storeOrder}/downloads/{storeOrderItemDownload}', [StoreOrderController::class, 'accountDownload'])->name('account.order.download');
        Route::post('/account/stemcraft/accounts', [MinecraftController::class, 'accountStore'])->name('account.stemcraft.store');
        Route::delete('/account/stemcraft/accounts/{minecraftAccount}', [MinecraftController::class, 'accountDestroy'])->name('account.stemcraft.destroy');
    });
    Route::post('/forum/{categorySlug}/topics', [ForumController::class, 'storeTopic'])->name('forum.topic.store');
    Route::put('/forum/{categorySlug}/{topicSlug}/title', [ForumController::class, 'updateTitle'])->name('forum.topic.title.update');
    Route::post('/forum/{categorySlug}/{topicSlug}/posts', [ForumController::class, 'storePost'])->name('forum.post.store');
    Route::put('/forum/{categorySlug}/{topicSlug}/posts/{forumPost}', [ForumController::class, 'updatePost'])->name('forum.post.update');
    Route::post('/forum/{categorySlug}/{topicSlug}/posts/{forumPost}/reaction', [ForumController::class, 'toggleReaction'])->name('forum.post.reaction');
    Route::post('/forum/{categorySlug}/{topicSlug}/posts/{forumPost}/report', [ForumController::class, 'reportPost'])->middleware('throttle:forum-report')->name('forum.post.report');
    Route::post('/forum/{categorySlug}/{topicSlug}/lock', [ForumController::class, 'toggleLock'])->name('forum.topic.lock');
    Route::post('/forum/{categorySlug}/{topicSlug}/pin', [ForumController::class, 'togglePin'])->name('forum.topic.pin');
    Route::delete('/forum/{categorySlug}/{topicSlug}', [ForumController::class, 'destroyTopic'])->name('forum.topic.destroy');
    Route::delete('/forum/{categorySlug}/{topicSlug}/posts/{forumPost}', [ForumController::class, 'destroyPost'])->name('forum.post.destroy');
    Route::get('/account/2fa', [AccountController::class, 'show_tfa'])->name('account.show.tfa');
    Route::get('/account/2fa/image', [AccountController::class, 'show_tfa_image'])->name('account.show.tfa.image');
    Route::post('/account/2fa', [AccountController::class, 'post_tfa'])->name('account.post.tfa');
    Route::post('/account/2fa/reset-backup-codes', [AccountController::class, 'post_tfa_reset_backup_codes'])->name('account.post.tfa.reset-backup-codes');
    Route::delete('/account/2fa', [AccountController::class, 'destroy_tfa'])->name('account.destroy.tfa');
});

Route::middleware('nocache')->group(function () {
    Route::get('/forum/{categorySlug}/{topicSlug}', [ForumController::class, 'showTopic'])->name('forum.topic.show');
    Route::get('/forum/{categorySlug}/{topicSlug}/snapshot', [ForumController::class, 'topicSnapshot'])->name('forum.topic.snapshot');
});

Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'postLogin'])->middleware('throttle:login')->name('login.store');
Route::get('/logout', [AuthController::class, 'showLogout'])->name('logout.show');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/register', [AuthController::class, 'showRegister'])->name('register');
Route::post('/register', [AuthController::class, 'postRegister'])->name('register.store');
Route::get('/update-email', [AuthController::class, 'updateEmail'])->name('update.email');
Route::get('/oauth/userinfo', UserInfoController::class)->middleware('auth:api')->name('openid.userinfo');

Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/contact', [ContactController::class, 'show'])->name('contact');
Route::post('/contact', [ContactController::class, 'send'])
    ->middleware(['throttle:public-form', 'form.guard:contact'])
    ->name('contact.send');

Route::get('/code-of-conduct', function () {
    return view('code-of-conduct');
})->name('code-of-conduct');

Route::get('/terms-conditions', function () {
    return view('terms-conditions');
})->name('terms-conditions');

Route::get('/privacy', function () {
    return view('privacy');
})->name('privacy');

Route::get('/media', [MediaController::class, 'index'])->name('media.index');
Route::get('/media/{media}', [MediaController::class, 'show'])->name('media.show');
Route::get('/media/download/{media}', [MediaController::class, 'download'])->name('media.download');

Route::middleware(['admin', 'nocache'])->group(function () {
    Route::get('/admin/media', [MediaController::class, 'admin_index'])->name('admin.media.index');
    Route::post('/admin/media/regenerate-missing-variants', [MediaController::class, 'admin_regenerate_missing_variants'])->name('admin.media.regenerate-missing-variants');
    Route::get('/admin/media/regenerate-missing-variants/status', [MediaController::class, 'admin_regenerate_missing_variants_status'])->name('admin.media.regenerate-missing-variants.status');
    Route::get('/admin/media/create', [MediaController::class, 'admin_create'])->name('admin.media.create');
    Route::post('/admin/media', [MediaController::class, 'admin_store'])->name('admin.media.store');
    Route::get('/admin/media/{media}', [MediaController::class, 'admin_edit'])->name('admin.media.edit');
    Route::put('/admin/media/{media}', [MediaController::class, 'admin_update'])->name('admin.media.update');
    Route::post('/admin/media/{media}/regenerate-variants', [MediaController::class, 'admin_regenerate_variants'])->name('admin.media.regenerate-variants');
    Route::post('/admin/media/{media}/delete-variant', [MediaController::class, 'admin_delete_variant'])->name('admin.media.delete-variant');
    Route::post('/admin/media/{media}/delete-variants', [MediaController::class, 'admin_delete_variants'])->name('admin.media.delete-variants');
    Route::delete('/admin/media/{media}', [MediaController::class, 'admin_destroy'])->name('admin.media.destroy');
    Route::get('/admin/locations', [LocationController::class, 'index'])->name('admin.location.index');
    Route::get('/admin/locations/create', [LocationController::class, 'create'])->name('admin.location.create');
    Route::post('/admin/locations', [LocationController::class, 'store'])->name('admin.location.store');
    Route::get('/admin/locations/{location}', [LocationController::class, 'edit'])->name('admin.location.edit');
    Route::put('/admin/locations/{location}', [LocationController::class, 'update'])->name('admin.location.update');
    Route::delete('/admin/locations/{location}', [LocationController::class, 'destroy'])->name('admin.location.destroy');

    //    Route::get('/admin/posts', [PostController::class, 'admin_index'])->name('admin.post.index');
    //    Route::get('/admin/posts/create', [PostController::class, 'admin_create'])->name('admin.post.create');
    //    Route::post('/admin/posts', [PostController::class, 'admin_store'])->name('admin.post.store');
    //    Route::get('/admin/posts/{post}', [PostController::class, 'admin_edit'])->name('admin.post.edit');
    //    Route::put('/admin/posts/{post}', [PostController::class, 'admin_update'])->name('admin.post.update');
    //    Route::delete('/admin/posts/{post}', [PostController::class, 'admin_destroy'])->name('admin.post.destroy');

    Route::get('/admin/users', [UserController::class, 'index'])->name('admin.user.index');
    Route::get('/admin/users/create', [UserController::class, 'create'])->name('admin.user.create');
    Route::post('/admin/users', [UserController::class, 'store'])->name('admin.user.store');
    Route::post('/admin/users/inline', [UserController::class, 'storeInline'])->name('admin.user.store-inline');
    Route::get('/admin/users/{user}', [UserController::class, 'edit'])->name('admin.user.edit');
    Route::get('/admin/users/{user}/payments', [UserController::class, 'payments'])->name('admin.user.payments');
    Route::put('/admin/users/{user}', [UserController::class, 'update'])->name('admin.user.update');
    Route::delete('/admin/users/{user}', [UserController::class, 'destroy'])->name('admin.user.destroy');
    Route::get('/admin/oauth-clients', [OAuthClientController::class, 'index'])->name('admin.oauth-clients.index');
    Route::post('/admin/oauth-clients', [OAuthClientController::class, 'store'])->name('admin.oauth-clients.store');
    Route::get('/admin/oauth-clients/{client}/edit', [OAuthClientController::class, 'edit'])->name('admin.oauth-clients.edit');
    Route::put('/admin/oauth-clients/{client}', [OAuthClientController::class, 'update'])->name('admin.oauth-clients.update');
    Route::post('/admin/oauth-clients/{client}/rotate-secret', [OAuthClientController::class, 'rotateSecret'])->name('admin.oauth-clients.rotate-secret');
    Route::delete('/admin/oauth-clients/{client}', [OAuthClientController::class, 'destroy'])->name('admin.oauth-clients.destroy');
    Route::get('/admin/classrooms', [AdminClassroomController::class, 'index'])->name('admin.classroom.index');
    Route::get('/admin/classrooms/create', [AdminClassroomController::class, 'create'])->name('admin.classroom.create');
    Route::post('/admin/classrooms', [AdminClassroomController::class, 'store'])->name('admin.classroom.store');
    Route::get('/admin/classrooms/{classSession}/duplicate', [AdminClassroomController::class, 'duplicate'])->name('admin.classroom.duplicate');
    Route::get('/admin/classrooms/{classSession}', [AdminClassroomController::class, 'edit'])->name('admin.classroom.edit');
    Route::put('/admin/classrooms/{classSession}', [AdminClassroomController::class, 'update'])->name('admin.classroom.update');
    Route::delete('/admin/classrooms/{classSession}', [AdminClassroomController::class, 'destroy'])->name('admin.classroom.destroy');
    Route::get('/admin/stemcraft/accounts', [MinecraftController::class, 'adminIndex'])->name('admin.stemcraft.index');
    Route::get('/admin/stemcraft/punishments', [MinecraftController::class, 'adminPunishmentsIndex'])->name('admin.stemcraft.punishments.index');
    Route::get('/admin/stemcraft/messages', [MinecraftController::class, 'adminMessagesIndex'])->name('admin.stemcraft.messages.index');
    Route::get('/admin/stemcraft/messages/snapshot', [MinecraftController::class, 'adminMessagesSnapshot'])->name('admin.stemcraft.messages.snapshot');
    Route::get('/admin/stemcraft/webhook-logs', [MinecraftController::class, 'adminWebhooksIndex'])->name('admin.stemcraft.webhook-logs.index');
    Route::get('/admin/stemcraft/webhook-logs/snapshot', [MinecraftController::class, 'adminWebhooksSnapshot'])->name('admin.stemcraft.webhook-logs.snapshot');
    Route::get('/admin/stemcraft/management', [MinecraftController::class, 'adminManagementIndex'])->name('admin.stemcraft.management.index');
    Route::get('/admin/stemcraft/management/snapshot', [MinecraftController::class, 'adminManagementSnapshot'])->name('admin.stemcraft.management.snapshot');
    Route::post('/admin/stemcraft/management', [MinecraftController::class, 'adminManagementExecute'])->name('admin.stemcraft.management.execute');
    Route::get('/admin/stemcraft/accounts/create', [MinecraftController::class, 'adminCreate'])->name('admin.stemcraft.create');
    Route::post('/admin/stemcraft/accounts', [MinecraftController::class, 'adminStore'])->name('admin.stemcraft.store');
    Route::get('/admin/stemcraft/accounts/{minecraftAccount}', [MinecraftController::class, 'adminEdit'])->name('admin.stemcraft.edit');
    Route::put('/admin/stemcraft/accounts/{minecraftAccount}', [MinecraftController::class, 'adminUpdate'])->name('admin.stemcraft.update');
    Route::post('/admin/stemcraft/punishments', [MinecraftController::class, 'adminPunishmentStore'])->name('admin.stemcraft.punishments.store');
    Route::delete('/admin/stemcraft/punishments/{minecraftPenalty}', [MinecraftController::class, 'adminPunishmentLift'])->name('admin.stemcraft.punishments.destroy');
    Route::post('/admin/stemcraft/webhook-logs/{minecraftWebhookLog}/retry', [MinecraftController::class, 'adminWebhookRetry'])->name('admin.stemcraft.webhook-logs.retry');
    Route::post('/admin/stemcraft/blacklist', [MinecraftController::class, 'adminBlacklistStore'])->name('admin.stemcraft.blacklist.store');
    Route::delete('/admin/stemcraft/blacklist/{minecraftBlacklistEntry}', [MinecraftController::class, 'adminBlacklistLift'])->name('admin.stemcraft.blacklist.destroy');

    Route::get('/admin/subscriptions', [EmailSubscriptionController::class, 'index'])->name('admin.subscription.index');
    Route::get('/admin/subscriptions/create', [EmailSubscriptionController::class, 'create'])->name('admin.subscription.create');
    Route::post('/admin/subscriptions', [EmailSubscriptionController::class, 'store'])->name('admin.subscription.store');
    Route::post('/admin/subscriptions/send-all-now', [EmailSubscriptionController::class, 'sendAllNow'])->name('admin.subscription.send-all-now');
    Route::post('/admin/subscriptions/send-test-now', [EmailSubscriptionController::class, 'sendTestNow'])->name('admin.subscription.send-test-now');
    Route::post('/admin/subscriptions/{subscription}/send-now', [EmailSubscriptionController::class, 'sendNow'])->name('admin.subscription.send-now');
    Route::get('/admin/subscriptions/{subscription}', [EmailSubscriptionController::class, 'edit'])->name('admin.subscription.edit');
    Route::put('/admin/subscriptions/{subscription}', [EmailSubscriptionController::class, 'update'])->name('admin.subscription.update');
    Route::delete('/admin/subscriptions/{subscription}', [EmailSubscriptionController::class, 'destroy'])->name('admin.subscription.destroy');

    Route::get('/admin/server', [ServerController::class, 'admin_index'])->name('admin.server.index');
    Route::get('/admin/server/backups', [ServerController::class, 'admin_backups'])->name('admin.server.backups');
    Route::get('/admin/server/options', [SiteOptionController::class, 'index'])->name('admin.site_option.index');
    Route::get('/admin/server/options/create', [SiteOptionController::class, 'create'])->name('admin.site_option.create');
    Route::post('/admin/server/options', [SiteOptionController::class, 'store'])->name('admin.site_option.store');
    Route::post('/admin/server/options/reset-defaults', [SiteOptionController::class, 'resetAllDefaults'])->name('admin.site_option.reset-defaults');
    Route::get('/admin/server/options/{siteOption}', [SiteOptionController::class, 'edit'])->name('admin.site_option.edit');
    Route::put('/admin/server/options/{siteOption}', [SiteOptionController::class, 'update'])->name('admin.site_option.update');
    Route::post('/admin/server/options/{siteOption}/reset-default', [SiteOptionController::class, 'resetDefault'])->name('admin.site_option.reset-default');
    Route::post('/admin/server/options/{siteOption}/generate-secret', [SiteOptionController::class, 'generateSecret'])->name('admin.site_option.generate-secret');
    Route::get('/admin/pages', [CustomPageController::class, 'adminIndex'])->name('admin.custom-page.index');
    Route::get('/admin/pages/create', [CustomPageController::class, 'adminCreate'])->name('admin.custom-page.create');
    Route::post('/admin/pages', [CustomPageController::class, 'adminStore'])->name('admin.custom-page.store');
    Route::get('/admin/pages/{customPage}', [CustomPageController::class, 'adminEdit'])->name('admin.custom-page.edit');
    Route::put('/admin/pages/{customPage}', [CustomPageController::class, 'adminUpdate'])->name('admin.custom-page.update');
    Route::delete('/admin/pages/{customPage}', [CustomPageController::class, 'adminDestroy'])->name('admin.custom-page.destroy');
    Route::get('/admin/forum/categories', [ForumCategoryController::class, 'index'])->name('admin.forum.category.index');
    Route::post('/admin/forum/categories', [ForumCategoryController::class, 'save'])->name('admin.forum.category.save');
    Route::get('/admin/forum/moderation', [ForumModerationController::class, 'show'])->name('admin.forum.moderation.show');
    Route::post('/admin/forum/moderation', [ForumModerationController::class, 'update'])->name('admin.forum.moderation.update');
    Route::post('/admin/forum/moderation/preview', [ForumModerationController::class, 'preview'])->name('admin.forum.moderation.preview');
    Route::get('/admin/server/log', [ServerController::class, 'admin_laravel_log'])->name('admin.server.log');
    Route::post('/admin/server/log/clear', [ServerController::class, 'admin_clear_log'])->name('admin.server.log.clear');
    Route::post('/admin/server/deploy/log/clear', [ServerController::class, 'admin_clear_deploy_log'])->name('admin.server.deploy.log.clear');
    Route::post('/admin/server/deploy', [ServerController::class, 'admin_deploy'])->name('admin.server.deploy');
    Route::get('/admin/server/deploy/log', [ServerController::class, 'admin_deploy_log'])->name('admin.server.deploy.log');
    Route::post('/admin/server/database/backup-now', [ServerController::class, 'admin_database_backup_now'])->name('admin.server.database.backup-now');
    Route::post('/admin/server/database/export', [ServerController::class, 'admin_database_export'])->name('admin.server.database.export');
    Route::post('/admin/server/database/import', [ServerController::class, 'admin_database_import'])->name('admin.server.database.import');
    Route::post('/admin/server/database/restore/{filename}', [ServerController::class, 'admin_database_restore'])->name('admin.server.database.restore');
    Route::get('/admin/server/database/download/{filename}', [ServerController::class, 'admin_database_download'])->name('admin.server.database.download');
    Route::delete('/admin/server/database/{filename}', [ServerController::class, 'admin_database_delete'])->name('admin.server.database.delete');
    Route::get('/admin/server/media/download-all', [ServerController::class, 'admin_media_download_all'])->name('admin.server.media.download-all');
    Route::get('/admin/server/finance/download-all', [ServerController::class, 'admin_finance_download_all'])->name('admin.server.finance.download-all');
    Route::get('/admin/server/orphans', [ServerController::class, 'admin_orphans'])->name('admin.server.orphans');
    Route::get('/admin/server/audit', [ServerController::class, 'admin_audit'])->name('admin.server.audit');
    Route::post('/admin/server/audit/prune', [ServerController::class, 'admin_audit_prune'])->name('admin.server.audit.prune');
    Route::post('/admin/server/orphans/scan', [ServerController::class, 'admin_orphans_scan'])->name('admin.server.orphans.scan');
    Route::get('/admin/server/orphans/file', [ServerController::class, 'admin_orphans_file'])->name('admin.server.orphans.file');
    Route::get('/admin/server/orphans/download-all', [ServerController::class, 'admin_orphans_download_all'])->name('admin.server.orphans.download-all');
    Route::post('/admin/server/orphans/delete-file', [ServerController::class, 'admin_orphans_delete_file'])->name('admin.server.orphans.delete-file');
    Route::post('/admin/server/orphans/delete-all', [ServerController::class, 'admin_orphans_delete_all'])->name('admin.server.orphans.delete-all');
    Route::get('/admin/server/square-events', [ServerController::class, 'admin_square_webhooks'])->name('admin.server.square-events');
    Route::post('/admin/server/square-events/sync', [ServerController::class, 'admin_square_webhooks_sync'])->name('admin.server.square-events.sync');
    Route::post('/admin/server/square-events/{event}/ignore', [ServerController::class, 'admin_square_webhook_ignore'])->name('admin.server.square-events.ignore');
    Route::delete('/admin/server/square-events/{event}/ignore', [ServerController::class, 'admin_square_webhook_unignore'])->name('admin.server.square-events.unignore');
    Route::get('/admin/server/square-events/{event}', [ServerController::class, 'admin_square_webhook_show'])->name('admin.server.square-events.show');
    Route::get('/admin/server/square-webhooks', [ServerController::class, 'admin_square_webhooks'])->name('admin.server.square-webhooks');
    Route::post('/admin/server/square-webhooks/sync', [ServerController::class, 'admin_square_webhooks_sync'])->name('admin.server.square-webhooks.sync');
    Route::post('/admin/server/square-webhooks/{event}/ignore', [ServerController::class, 'admin_square_webhook_ignore'])->name('admin.server.square-webhooks.ignore');
    Route::delete('/admin/server/square-webhooks/{event}/ignore', [ServerController::class, 'admin_square_webhook_unignore'])->name('admin.server.square-webhooks.unignore');
    Route::get('/admin/server/square-webhooks/{event}', [ServerController::class, 'admin_square_webhook_show'])->name('admin.server.square-webhooks.show');
    Route::get('/admin/server/sent-emails', [ServerController::class, 'admin_sent_emails'])->name('admin.server.sent-emails');
    Route::get('/admin/analytics', [AnalyticsController::class, 'index'])->name('admin.analytics.index');
    Route::post('/admin/analytics/prune', [AnalyticsController::class, 'prune'])->name('admin.analytics.prune');

    Route::get('/admin/workshops', [WorkshopController::class, 'admin_index'])->name('admin.workshop.index');
    Route::get('/admin/workshops/create', [WorkshopController::class, 'admin_create'])->name('admin.workshop.create');
    Route::get('/admin/workshops/{workshop}/duplicate', [WorkshopController::class, 'admin_duplicate'])->name('admin.workshop.duplicate');
    Route::get('/admin/workshops/{workshop}/tickets', [WorkshopController::class, 'admin_tickets'])->name('admin.workshop.tickets');
    Route::post('/admin/workshops/{workshop}/tickets', [WorkshopController::class, 'admin_tickets_store'])->name('admin.workshop.tickets.store');
    Route::get('/admin/workshops/{workshop}/tickets/pdf', [WorkshopController::class, 'admin_tickets_pdf'])->name('admin.workshop.tickets.pdf');
    Route::post('/admin/workshops/{workshop}/tickets/email', [WorkshopController::class, 'admin_tickets_email'])->name('admin.workshop.tickets.email');
    Route::get('/admin/workshops/{workshop}/attendance', [WorkshopController::class, 'admin_attendance'])->name('admin.workshop.attendance');
    Route::get('/admin/workshops/{workshop}/attendance/csv', [WorkshopController::class, 'admin_attendance_csv'])->name('admin.workshop.attendance.csv');
    Route::get('/admin/workshops/{workshop}/attendance/pdf', [WorkshopController::class, 'admin_attendance_pdf'])->name('admin.workshop.attendance.pdf');
    Route::post('/admin/workshops/{workshop}/attendance/tickets', [WorkshopController::class, 'admin_attendance_tickets'])->name('admin.workshop.attendance.tickets');
    Route::post('/admin/workshops/{workshop}/attendance/payments', [WorkshopController::class, 'admin_attendance_payments'])->name('admin.workshop.attendance.payments');
    Route::post('/admin/workshops/{workshop}/attendance/dropins', [WorkshopController::class, 'admin_attendance_dropin_store'])->name('admin.workshop.attendance.dropin.store');
    Route::post('/admin/workshops/{workshop}/attendance/dropins/sync', [WorkshopController::class, 'admin_attendance_dropin_sync'])->name('admin.workshop.attendance.dropin.sync');
    Route::put('/admin/workshops/{workshop}/attendance/dropins/{attendance}', [WorkshopController::class, 'admin_attendance_dropin_update'])->name('admin.workshop.attendance.dropin.update');
    Route::post('/admin/workshops/{workshop}/attendance/dropins/{attendance}/delete', [WorkshopController::class, 'admin_attendance_dropin_destroy'])->name('admin.workshop.attendance.dropin.destroy');
    Route::get('/admin/workshops/{workshop}/interests', [WorkshopController::class, 'admin_interests'])->name('admin.workshop.interests');
    Route::get('/admin/workshops/{workshop}/pick-list', [WorkshopPickListController::class, 'show'])->name('admin.workshop.pick-list');
    Route::post('/admin/workshops/{workshop}/pick-list', [WorkshopPickListController::class, 'save'])->name('admin.workshop.pick-list.save');
    Route::get('/admin/workshops/{workshop}/pick-list/pdf', [WorkshopPickListController::class, 'pdf'])->name('admin.workshop.pick-list.pdf');
    Route::get('/admin/tickets', [TicketController::class, 'adminIndex'])->name('admin.ticket.index');
    Route::post('/admin/tickets/cancel/bulk', [TicketController::class, 'adminBulkCancel'])->name('admin.ticket.cancel.bulk');
    Route::post('/admin/tickets/{ticket}/cancel', [TicketController::class, 'adminCancel'])->name('admin.ticket.cancel');
    Route::post('/admin/workshops', [WorkshopController::class, 'admin_store'])->name('admin.workshop.store');
    Route::get('/admin/workshops/{workshop}', [WorkshopController::class, 'admin_edit'])->name('admin.workshop.edit');
    Route::put('/admin/workshops/{workshop}', [WorkshopController::class, 'admin_update'])->name('admin.workshop.update');
    Route::delete('/admin/workshops/{workshop}', [WorkshopController::class, 'admin_destroy'])->name('admin.workshop.destroy');

    Route::get('/admin/expenses', [ExpenseController::class, 'index'])->name('admin.expense.index');
    Route::get('/admin/expenses/create', [ExpenseController::class, 'create'])->name('admin.expense.create');
    Route::post('/admin/expenses', [ExpenseController::class, 'store'])->name('admin.expense.store');
    Route::get('/admin/expenses/{expense}', [ExpenseController::class, 'edit'])->name('admin.expense.edit');
    Route::put('/admin/expenses/{expense}', [ExpenseController::class, 'update'])->name('admin.expense.update');
    Route::delete('/admin/expenses/{expense}', [ExpenseController::class, 'destroy'])->name('admin.expense.destroy');
    Route::get('/admin/expenses/{expense}/document', [ExpenseController::class, 'viewDocument'])->name('admin.expense.document.view');
    Route::get('/admin/expenses/{expense}/document/download', [ExpenseController::class, 'downloadDocument'])->name('admin.expense.document.download');
    Route::delete('/admin/expenses/{expense}/document', [ExpenseController::class, 'removeDocument'])->name('admin.expense.document.remove');
    Route::post('/admin/finance-files/upload', [FinanceFileController::class, 'upload'])->name('admin.finance-file.upload');
    Route::get('/admin/finance-files/{financeFile}', [FinanceFileController::class, 'view'])->name('admin.finance-file.view');
    Route::get('/admin/finance-files/{financeFile}/download', [FinanceFileController::class, 'download'])->name('admin.finance-file.download');
    Route::get('/admin/finance-files/{financeFile}/impact', [FinanceFileController::class, 'impact'])->name('admin.finance-file.impact');
    Route::post('/admin/finance-files/{financeFile}/association', [FinanceFileController::class, 'updateAssociation'])->name('admin.finance-file.association');

    Route::get('/admin/payments', [PaymentController::class, 'index'])->name('admin.payment.index');
    Route::get('/admin/payments/refunds', [PaymentController::class, 'credits'])->name('admin.payment.refunds');
    Route::get('/admin/payments/create', [PaymentController::class, 'create'])->name('admin.payment.create');
    Route::post('/admin/payments', [PaymentController::class, 'store'])->name('admin.payment.store');
    Route::get('/admin/payments/{payment}', [PaymentController::class, 'edit'])->name('admin.payment.edit');
    Route::get('/admin/payments/{payment}/receipt', [PaymentController::class, 'receiptPdf'])->name('admin.payment.receipt');
    Route::put('/admin/payments/{payment}', [PaymentController::class, 'update'])->name('admin.payment.update');
    Route::delete('/admin/payments/{payment}', [PaymentController::class, 'destroy'])->name('admin.payment.destroy');
    Route::post('/admin/payments/{payment}/square/charge', [PaymentController::class, 'chargeWithSquare'])->name('admin.payment.square.charge');
    Route::post('/admin/payments/{payment}/square/refund', [PaymentController::class, 'refundWithSquare'])->name('admin.payment.square.refund');
    Route::post('/admin/payments/{payment}/refund/manual', [PaymentController::class, 'refundManual'])->name('admin.payment.refund.manual');
    Route::post('/admin/payments/refunds/{manualRefund}/complete', [PaymentController::class, 'completeManualRefund'])->name('admin.payment.refunds.complete');

    Route::get('/admin/invoices', [InvoiceController::class, 'index'])->name('admin.invoice.index');
    Route::get('/admin/invoices/create', [InvoiceController::class, 'create'])->name('admin.invoice.create');
    Route::post('/admin/invoices', [InvoiceController::class, 'store'])->name('admin.invoice.store');
    Route::get('/admin/invoices/{invoice}', [InvoiceController::class, 'edit'])->name('admin.invoice.edit');
    Route::put('/admin/invoices/{invoice}', [InvoiceController::class, 'update'])->name('admin.invoice.update');
    Route::delete('/admin/invoices/{invoice}', [InvoiceController::class, 'destroy'])->name('admin.invoice.destroy');
    Route::get('/admin/invoices/{invoice}/pdf', [InvoiceController::class, 'pdf'])->name('admin.invoice.pdf');
    Route::post('/admin/invoices/{invoice}/email', [InvoiceController::class, 'emailPdf'])->name('admin.invoice.email');
    Route::post('/admin/invoices/{invoice}/email-payment-link', [InvoiceController::class, 'emailPaymentLink'])->name('admin.invoice.email-payment-link');
    Route::post('/admin/invoices/{invoice}/payment-link', [InvoiceController::class, 'paymentLink'])->name('admin.invoice.payment-link');
    Route::get('/admin/invoices/{invoice}/adjustments', [InvoiceController::class, 'adjustmentIndex'])->name('admin.invoice.short.adjustments');
    Route::get('/admin/invoices/{invoice}/adjustments/create', [TaxAdjustmentController::class, 'create'])->name('admin.tax_adjustment.create');
    Route::post('/admin/invoices/{invoice}/adjustments', [TaxAdjustmentController::class, 'store'])->name('admin.tax_adjustment.store');
    Route::get('/admin/invoices/{invoice}/adjustments/{taxAdjustment}', [TaxAdjustmentController::class, 'edit'])->name('admin.tax_adjustment.edit');
    Route::get('/admin/invoices/{invoice}/adjustments/{taxAdjustment}/pdf', [TaxAdjustmentController::class, 'pdf'])->name('admin.tax_adjustment.pdf');
    Route::post('/admin/invoices/{invoice}/adjustments/{taxAdjustment}/email', [TaxAdjustmentController::class, 'emailPdf'])->name('admin.tax_adjustment.email');
    Route::put('/admin/invoices/{invoice}/adjustments/{taxAdjustment}', [TaxAdjustmentController::class, 'update'])->name('admin.tax_adjustment.update');

    Route::get('/admin/quotes', [QuoteController::class, 'index'])->name('admin.quote.index');
    Route::get('/admin/quotes/create', [QuoteController::class, 'create'])->name('admin.quote.create');
    Route::post('/admin/quotes', [QuoteController::class, 'store'])->name('admin.quote.store');
    Route::get('/admin/quotes/{quote}', [QuoteController::class, 'edit'])->name('admin.quote.edit');
    Route::put('/admin/quotes/{quote}', [QuoteController::class, 'update'])->name('admin.quote.update');
    Route::delete('/admin/quotes/{quote}', [QuoteController::class, 'destroy'])->name('admin.quote.destroy');
    Route::get('/admin/quotes/{quote}/pdf', [QuoteController::class, 'pdf'])->name('admin.quote.pdf');
    Route::post('/admin/quotes/{quote}/email', [QuoteController::class, 'emailPdf'])->name('admin.quote.email');
    Route::post('/admin/quotes/{quote}/create-invoice', [QuoteController::class, 'createInvoice'])->name('admin.quote.create-invoice');
    Route::get('/admin/store/products', [ShopProductController::class, 'index'])->name('admin.shop.product.index');
    Route::get('/admin/store/products/create', [ShopProductController::class, 'create'])->name('admin.shop.product.create');
    Route::post('/admin/store/products', [ShopProductController::class, 'store'])->name('admin.shop.product.store');
    Route::get('/admin/store/products/{product}', [ShopProductController::class, 'edit'])->name('admin.shop.product.edit');
    Route::put('/admin/store/products/{product}', [ShopProductController::class, 'update'])->name('admin.shop.product.update');
    Route::delete('/admin/store/products/{product}', [ShopProductController::class, 'destroy'])->name('admin.shop.product.destroy');
    Route::get('/admin/store/settings', [ShopSettingsController::class, 'edit'])->name('admin.shop.settings.edit');
    Route::put('/admin/store/settings', [ShopSettingsController::class, 'update'])->name('admin.shop.settings.update');
    Route::get('/admin/store/coupons', [ShopCouponController::class, 'index'])->name('admin.shop.coupon.index');
    Route::get('/admin/store/coupons/create', [ShopCouponController::class, 'create'])->name('admin.shop.coupon.create');
    Route::post('/admin/store/coupons', [ShopCouponController::class, 'store'])->name('admin.shop.coupon.store');
    Route::get('/admin/store/coupons/{coupon}', [ShopCouponController::class, 'edit'])->name('admin.shop.coupon.edit');
    Route::put('/admin/store/coupons/{coupon}', [ShopCouponController::class, 'update'])->name('admin.shop.coupon.update');
    Route::delete('/admin/store/coupons/{coupon}', [ShopCouponController::class, 'destroy'])->name('admin.shop.coupon.destroy');
    Route::get('/admin/store/orders', [ShopAdminOrderController::class, 'index'])->name('admin.shop.order.index');
    Route::get('/admin/store/orders/{storeOrder}', [ShopAdminOrderController::class, 'edit'])->name('admin.shop.order.edit');
    Route::put('/admin/store/orders/{storeOrder}', [ShopAdminOrderController::class, 'update'])->name('admin.shop.order.update');
    Route::post('/admin/store/orders/{storeOrder}/quote', [ShopAdminOrderController::class, 'sendQuote'])->name('admin.shop.order.quote.send');
    Route::post('/admin/store/orders/{storeOrder}/items/{storeOrderItem}/cancel', [ShopAdminOrderController::class, 'cancelItem'])->name('admin.shop.order.item.cancel');
    Route::post('/admin/store/orders/{storeOrder}/items/{storeOrderItem}/tracking', [ShopAdminOrderController::class, 'storeItemTracking'])->name('admin.shop.order.item.tracking.store');
    Route::redirect('/admin/shop', '/admin/store', 302);
    Route::redirect('/admin/shop/{path}', '/admin/store/{path}', 302)->where('path', '.*');
    Route::get('/admin/pick-list-templates', [PickListTemplateController::class, 'index'])->name('admin.pick-list-template.index');
    Route::get('/admin/pick-list-templates/create', [PickListTemplateController::class, 'create'])->name('admin.pick-list-template.create');
    Route::post('/admin/pick-list-templates', [PickListTemplateController::class, 'store'])->name('admin.pick-list-template.store');
    Route::get('/admin/pick-list-templates/{pickListTemplate}', [PickListTemplateController::class, 'edit'])->name('admin.pick-list-template.edit');
    Route::put('/admin/pick-list-templates/{pickListTemplate}', [PickListTemplateController::class, 'update'])->name('admin.pick-list-template.update');
    Route::post('/admin/pick-list-templates/{pickListTemplate}/duplicate', [PickListTemplateController::class, 'duplicate'])->name('admin.pick-list-template.duplicate');
    Route::delete('/admin/pick-list-templates/{pickListTemplate}', [PickListTemplateController::class, 'destroy'])->name('admin.pick-list-template.destroy');
    Route::get('/admin/bas', [BasController::class, 'index'])->name('admin.bas.index');
    Route::get('/admin/bas/export/csv', [BasController::class, 'exportCsv'])->name('admin.bas.export.csv');
    Route::get('/admin/bas/export/pdf', [BasController::class, 'exportPdf'])->name('admin.bas.export.pdf');
    Route::get('/admin/bas/export/download-all', [BasController::class, 'downloadAll'])->name('admin.bas.export.download-all');

});

Route::fallback([CustomPageController::class, 'fallback']);
