[program:stemmechanics-analytics]
directory=/var/www/stemmechanics
command=php artisan queue:work --queue=analytics --sleep=2 --tries=3 --timeout=20 --max-time=3600
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=60
redirect_stderr=true
stdout_logfile=/var/log/stemmechanics-analytics.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
