<div class="grid gap-4 sm:grid-cols-3">@foreach(['Time target' => $earned, 'Drawings paid' => $paid, 'Still to draw' => max(0, $earned - $paid)] as $title => $amount)<x-finance.panel :title="$title"><p class="text-2xl font-semibold">{{ money($amount / 100) }}</p></x-finance.panel>@endforeach</div>
<x-finance.panel title="Prepare a drawing">
    <p class="mb-4">Available now: <strong>{{ money(max(0, min($earned - $paid - $pending, $cash['available'])) / 100) }}</strong>. Pending transfers: {{ money($pending / 100) }}. The remaining time target carries forward until cash is available.</p>
    <form method="POST" action="{{ route('admin.finance.drawing') }}">@csrf<input type="hidden" name="token" value="{{ \Illuminate\Support\Str::uuid() }}"><x-ui.input name="amount" label="Amount to transfer" type="number" min="0.01" step="0.01" required /><x-finance.save>Prepare drawing</x-finance.save></form>
    <p class="mt-3 text-sm text-slate-600">This records a planned owner drawing. Make the transfer in your bank, then mark it transferred below. It does not send money or create a wage expense.</p>
</x-finance.panel>
<x-finance.panel title="Drawing history">
    @forelse($drawings as $drawing)<div class="mb-4 rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-center justify-between gap-3"><p>{{ money($drawing->cents / 100) }} · {{ $drawing->created_at }} @if($drawing->reference) · {{ $drawing->reference }}@endif</p><x-ui.badge :color="$drawing->status === 'paid' ? 'green' : 'slate'">{{ ucfirst($drawing->status) }}</x-ui.badge></div>
        @if($drawing->status === 'pending')<form method="POST" action="{{ route('admin.finance.drawingStatus', $drawing->id) }}" class="mt-4">@csrf<input type="hidden" name="status" value="paid"><div class="grid gap-x-4 sm:grid-cols-2"><x-ui.input name="paid_on" label="Transfer date" type="date" :value="now()->toDateString()" required /><x-ui.input name="reference" label="Bank reference" required /></div><x-finance.save>Mark transferred</x-finance.save></form><form method="POST" action="{{ route('admin.finance.drawingStatus', $drawing->id) }}">@csrf<input type="hidden" name="status" value="cancelled"><x-ui.button type="submit" color="danger">Cancel drawing</x-ui.button></form>@endif
    </div>@empty<p>No drawings recorded.</p>@endforelse
    <x-ui.list-pagination :paginator="$drawings" label="drawings" />
</x-finance.panel>
