<x-finance.panel title="Opening balances and automation">
    <p class="mb-4 text-sm text-slate-600">Use the bank balance immediately before the opening date. Payments and expenses on that date onwards are added automatically. Opening category reserves and GST must reflect what remains after past spending, drawings and BAS payments. Historical allocations before this date are reporting only.</p>
    <form method="POST" action="{{ route('admin.finance.settings') }}">@csrf
        <div class="grid gap-x-5 sm:grid-cols-2"><x-ui.input name="opening_date" label="Opening date" type="date" :value="$cash['settings']->opening_date" required /><x-ui.input name="opening_cash" label="Opening bank balance" type="number" step="0.01" :value="$cash['settings']->opening_cash_cents / 100" required /><x-ui.input name="opening_gst" label="Outstanding GST (negative if refundable)" type="number" step="0.01" :value="$cash['settings']->opening_gst_cents / 100" required /><x-ui.input name="buffer" label="Minimum business cash buffer" type="number" step="0.01" min="0" :value="$cash['settings']->buffer_cents / 100" required /><x-ui.input name="fortnight_anchor" label="First day of a pay fortnight" type="date" :value="$cash['settings']->fortnight_anchor" required /></div>
        <h3 class="mb-3 text-lg font-semibold">Opening category reserves</h3><div class="grid gap-x-4 sm:grid-cols-2 lg:grid-cols-4">@foreach($categories as $category)<x-ui.input :name="'reserves['.$category->id.']'" :label="$category->name" type="number" step="0.01" min="0" :value="$category->opening_cents / 100" required />@endforeach</div>
        <x-ui.checkbox name="auto_budget" value="1" :checked="$cash['settings']->auto_budget" label="Automatically create budgets for linked workshops from the opening date onwards" />
        <p class="my-3 text-sm text-slate-600">The hourly task chooses the pricing version effective on the workshop date. Existing budgets and overrides are preserved. Review travel and attendance assumptions in allocations.</p>
        <x-ui.checkbox name="confirmed" value="1" label="I have reconciled these balances and confirmed that our BAS uses cash accounting" />
        <x-finance.save>Save finance settings</x-finance.save>
    </form>
</x-finance.panel>
