@php
    $kitDeleteBlockers = $kitDeleteBlockers ?? [];
    $kitArchiveBlockers = $kitArchiveBlockers ?? [];
    $assemblyPlan = $assemblyPlan ?? null;
    $kitMastTitle = $kit->exists
        ? 'Edit '.$kit->name.(preg_match('/\bkit$/i', trim((string) $kit->name)) ? '' : ' Kit')
        : 'Create kit';
    $kitName = old('name', $kit->name ?? '');
    $kitFormDirty = old('components') !== null || old('name') !== null || old('sku') !== null || old('notes') !== null || old('status') !== null;
    $skuValue = old('sku', $kit->sku ?? '');
    $skuWasTouched = trim((string) $skuValue) !== '';
    $skuAutoGenerated = (bool) old('sku_auto_generated', false);
    $componentCatalog = collect($stockItems ?? [])->reject(fn ($item) => $kit->exists && (int) $item->id === (int) $kit->id)->map(fn ($item) => [
        'id' => (int) $item->id,
        'name' => (string) $item->linkLabel(),
        'sku' => (string) ($item->sku ?? ''),
        'unit' => (string) $item->unit,
        'is_kit' => (bool) $item->is_kit,
        'group_name' => (string) ($item->group?->name ?? ''),
        'variant_name' => (string) ($item->variant_name ?? ''),
        'replacement_unit_cost_ex_tax' => $item->replacementCost(),
    ])->values()->all();
    $components = old('components');
    if ($components === null) {
        $components = $kit->exists
            ? $kit->kitComponents->map(fn ($component) => [
                'stock_item_id' => (string) $component->component_stock_item_id,
                'item_name' => (string) ($component->component?->linkLabel() ?? ''),
                'quantity' => (string) $component->quantity,
                'note' => (string) ($component->note ?? ''),
            ])->values()->all()
            : [['stock_item_id' => '', 'item_name' => '', 'quantity' => '1', 'note' => '']];
    }
@endphp
<x-layout>
    <div
        x-data="{
            kitFormDirty: @js($kitFormDirty),
            assemblyDialogLoading: false,
            assemblyDialogError: '',
            assemblyPlanUpdateTimer: null,
            assemblyPlanUpdateController: null,
            async openAssemblyDialog(form) {
                if (this.kitFormDirty || this.assemblyDialogLoading) return;
                const quantityField = form.elements.namedItem('quantity');
                if (quantityField && !String(quantityField.value).trim()) quantityField.value = '1';
                const quantity = quantityField?.value || '1';
                const url = new URL(form.action, window.location.href);
                url.searchParams.set('quantity', quantity);
                this.assemblyDialogLoading = true;
                this.assemblyDialogError = '';
                try {
                    const response = await fetch(url, {
                        headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' },
                    });
                    if (!response.ok) {
                        const payload = await response.json().catch(() => ({}));
                        this.assemblyDialogError = Object.values(payload.errors || {}).flat()[0] || 'Could not load the assembly plan. Check the quantity and try again.';
                        return;
                    }
                    this.$refs.assemblyDialogContent.innerHTML = await response.text();
                    this.$refs.assemblyDialog.showModal();
                    this.$nextTick(() => this.$refs.assemblyDialog.querySelector('[data-assembly-quantity]')?.focus());
                } catch {
                    this.assemblyDialogError = 'Could not load the assembly plan. Try again.';
                } finally {
                    this.assemblyDialogLoading = false;
                }
            },
            scheduleAssemblyPlanRefresh(quantity) {
                if (this.assemblyPlanUpdateTimer !== null) window.clearTimeout(this.assemblyPlanUpdateTimer);
                this.assemblyPlanUpdateTimer = null;
                const count = Number(quantity);
                if (!Number.isInteger(count) || count < 1 || count > 100000) {
                    this.assemblyPlanUpdateController?.abort();
                    return;
                }
                const currentPlan = this.$refs.assemblyDialogContent.querySelector('input[name=quantity]')?.value;
                if (Number(currentPlan) === count) {
                    this.assemblyPlanUpdateController?.abort();
                    return;
                }
                this.assemblyPlanUpdateTimer = window.setTimeout(() => {
                    this.assemblyPlanUpdateTimer = null;
                    this.refreshAssemblyPlan(count);
                }, 350);
            },
            async refreshAssemblyPlan(quantity) {
                const currentQuantityField = this.$refs.assemblyDialogContent.querySelector('[data-assembly-quantity]');
                if (!currentQuantityField || Number(currentQuantityField.value) !== quantity) return;
                this.assemblyPlanUpdateController?.abort();
                const controller = new AbortController();
                this.assemblyPlanUpdateController = controller;
                this.assemblyDialogLoading = true;
                this.assemblyDialogError = '';
                const url = new URL(this.$refs.assemblyPreviewForm.action, window.location.href);
                url.searchParams.set('quantity', String(quantity));
                try {
                    const response = await fetch(url, {
                        signal: controller.signal,
                        headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' },
                    });
                    const currentField = this.$refs.assemblyDialogContent.querySelector('[data-assembly-quantity]');
                    if (!currentField || Number(currentField.value) !== quantity) return;
                    if (!response.ok) {
                        const payload = await response.json().catch(() => ({}));
                        this.assemblyDialogError = Object.values(payload.errors || {}).flat()[0] || 'Could not update the material quantities.';
                        return;
                    }
                    const html = await response.text();
                    if (Number(this.$refs.assemblyDialogContent.querySelector('[data-assembly-quantity]')?.value) !== quantity) return;
                    const parsed = new DOMParser().parseFromString(html, 'text/html');
                    const nextTable = parsed.querySelector('[data-assembly-table]');
                    const form = this.$refs.assemblyDialogContent.querySelector('form');
                    const currentTable = form?.querySelector('[data-assembly-table]');
                    if (!nextTable || !currentTable || !form) throw new Error('Assembly plan response was incomplete.');

                    const manualUsage = Array.from(form.querySelectorAll('input[name^=actual_usage]'))
                        .filter((input) => input.dataset.userEdited === 'true')
                        .map((input) => [input.name, input.value]);
                    currentTable.replaceWith(nextTable);
                    const planField = form.elements.namedItem('quantity');
                    const completedField = form.elements.namedItem('completed_quantity');
                    if (planField) planField.value = String(quantity);
                    if (completedField) completedField.max = String(quantity);
                    for (const [name, value] of manualUsage) {
                        const input = Array.from(form.querySelectorAll('input[name^=actual_usage]')).find((field) => field.name === name);
                        if (input) {
                            input.value = value;
                            input.dataset.userEdited = 'true';
                        }
                    }
                    if (this.$refs.assemblyPlannedQuantity) this.$refs.assemblyPlannedQuantity.value = String(quantity);
                } catch (error) {
                    const field = this.$refs.assemblyDialogContent.querySelector('[data-assembly-quantity]');
                    if (error.name !== 'AbortError' && this.assemblyPlanUpdateController === controller && Number(field?.value) === quantity) {
                        this.assemblyDialogError = 'Could not update the material quantities. Try again.';
                    }
                } finally {
                    if (this.assemblyPlanUpdateController === controller) {
                        this.assemblyPlanUpdateController = null;
                        this.assemblyDialogLoading = false;
                    }
                }
            },
            handleAssemblyDialogInput(event) {
                this.assemblyDialogError = '';
                if (event.target.matches('input[name^=actual_usage]')) {
                    event.target.dataset.userEdited = 'true';
                    event.target.closest('td')?.querySelector('[data-assembly-validation-error]')?.remove();
                    this.$refs.assemblyDialogContent.querySelector('[data-assembly-validation-error]')?.remove();
                }
                if (event.target.matches('[data-assembly-quantity]')) {
                    this.$refs.assemblyDialogContent.querySelectorAll('[data-assembly-validation-error]').forEach((error) => error.remove());
                    this.scheduleAssemblyPlanRefresh(event.target.value);
                }
            },
            submitAssemblyDialog(event) {
                const form = event.target;
                const completed = form.elements.namedItem('completed_quantity');
                const planned = form.elements.namedItem('quantity');
                if (this.assemblyDialogLoading) {
                    event.preventDefault();
                    return;
                }
                if (completed && planned && Number(completed.value) > 0 && Number(completed.value) !== Number(planned.value)) {
                    event.preventDefault();
                    this.scheduleAssemblyPlanRefresh(completed.value);
                }
            },
            closeAssemblyDialog() {
                if (this.assemblyPlanUpdateTimer !== null) window.clearTimeout(this.assemblyPlanUpdateTimer);
                this.assemblyPlanUpdateTimer = null;
                this.assemblyPlanUpdateController?.abort();
                this.assemblyPlanUpdateController = null;
                this.assemblyDialogLoading = false;
                this.assemblyDialogError = '';
                if (this.$refs.assemblyDialog?.open) this.$refs.assemblyDialog.close();
            },
        }"
        x-on:kit-form-dirty.window="kitFormDirty = true"
    >
    <x-mast backRoute="admin.shop.stock.kits" backTitle="Kits" :tabs="$stockTabs">
        {{ $kitMastTitle }}
    </x-mast>

    <x-container class="mt-4" inner-class="space-y-6">
        @error('kit')
            <div class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">{{ $message }}</div>
        @enderror
        @error('status')
            <div class="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900" role="alert">{{ $message }}</div>
        @enderror
        <form
            id="stock-kit-editor"
            method="POST"
            action="{{ $kit->exists ? route('admin.shop.stock.kit.update', $kit) : route('admin.shop.stock.kit.store') }}"
            class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"
            x-on:input="$dispatch('kit-form-dirty')"
            x-on:change="$dispatch('kit-form-dirty')"
            x-data="{
                name: @js($kitName),
                sku: @js($skuValue),
                skuTouched: @js($skuWasTouched),
                skuAutoGenerated: @js($skuAutoGenerated),
                stockItems: @js($componentCatalog),
                components: @js($components),
                mobileNoteIndex: null,
                mobileNoteDraft: '',
                slugify(value) {
                    return String(value || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 120);
                },
                generateSku() {
                    if (!this.skuTouched && !String(this.sku || '').trim()) {
                        this.sku = this.slugify(this.name);
                        this.skuAutoGenerated = true;
                    }
                },
                editSku() {
                    this.skuTouched = String(this.sku || '').trim() !== '';
                    this.skuAutoGenerated = false;
                },
                item(stockItemId) {
                    return this.stockItems.find((item) => String(item.id) === String(stockItemId ?? '')) || null;
                },
                lineCost(component) {
                    const item = this.item(component.stock_item_id);
                    const replacementCost = item?.replacement_unit_cost_ex_tax;
                    if (replacementCost === null || replacementCost === undefined) return null;
                    const unitCost = Number(replacementCost);
                    const quantity = Number.parseFloat(String(component.quantity ?? ''));
                    if (!Number.isFinite(unitCost) || !Number.isFinite(quantity) || quantity <= 0) return null;
                    return Math.round(unitCost * quantity * 10000) / 10000;
                },
                totalCost() {
                    const savedComponents = this.components.filter((component) => !this.isBlankComponent(component));
                    if (!savedComponents.length) return null;
                    let total = 0;
                    for (const component of savedComponents) {
                        const cost = this.lineCost(component);
                        if (cost === null || !component.stock_item_id) return null;
                        total += cost;
                    }
                    return Math.round(total * 10000) / 10000;
                },
                formatAud(value) {
                    return new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD', minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
                },
                seededBlankComponent() {
                    return { stock_item_id: '', item_name: '', quantity: '1', note: '' };
                },
                isBlankComponent(component) {
                    return !String(component?.stock_item_id ?? '').trim() && !String(component?.item_name ?? '').trim();
                },
                hasSingleTrailingBlank() {
                    const blankCount = this.components.filter((component) => this.isBlankComponent(component)).length;
                    return blankCount === 1 && this.isBlankComponent(this.components[this.components.length - 1]);
                },
                ensureSingleTrailingBlank() {
                    const savedComponents = this.components.filter((component) => !this.isBlankComponent(component));
                    this.components = [...savedComponents, this.seededBlankComponent()];
                },
                handleComponentChange(index) {
                    if (index === this.components.length - 1 && !this.isBlankComponent(this.components[index])) {
                        this.components.push(this.seededBlankComponent());
                        return;
                    }
                    if (!this.hasSingleTrailingBlank()) this.ensureSingleTrailingBlank();
                },
                selectComponentStockItem(index) {
                    const component = this.components[index];
                    if (!component) return;
                    component.item_name = this.item(component.stock_item_id)?.name || '';
                    this.handleComponentChange(index);
                },
                openComponentNote(index) {
                    const component = this.components[index];
                    if (!component) return;
                    this.mobileNoteIndex = index;
                    this.mobileNoteDraft = String(component.note || '');
                    this.$nextTick(() => this.$refs.componentNoteDialog?.showModal());
                },
                saveComponentNote() {
                    const index = this.mobileNoteIndex;
                    if (index === null || !this.components[index]) return;
                    this.components[index].note = String(this.mobileNoteDraft || '').trim();
                    this.handleComponentChange(index);
                    this.$dispatch('kit-form-dirty');
                    this.$refs.componentNoteDialog?.close();
                },
                closeComponentNote() {
                    if (this.$refs.componentNoteDialog?.open) this.$refs.componentNoteDialog.close();
                },
                removeComponent(index) {
                    this.components.splice(index, 1);
                    this.ensureSingleTrailingBlank();
                },
                moveComponentUp(index) {
                    if (index <= 0 || this.isBlankComponent(this.components[index])) return;
                    [this.components[index - 1], this.components[index]] = [this.components[index], this.components[index - 1]];
                    if (!this.hasSingleTrailingBlank()) this.ensureSingleTrailingBlank();
                },
                moveComponentDown(index) {
                    const lastSavedIndex = this.components.length - 2;
                    if (index >= lastSavedIndex || this.isBlankComponent(this.components[index])) return;
                    [this.components[index + 1], this.components[index]] = [this.components[index], this.components[index + 1]];
                    if (!this.hasSingleTrailingBlank()) this.ensureSingleTrailingBlank();
                },
            }"
            x-init="ensureSingleTrailingBlank()"
        >
            @csrf
            @if($kit->exists) @method('PUT') @endif
            <input type="hidden" name="sku_auto_generated" x-bind:value="skuAutoGenerated ? '1' : '0'">
            <h2 class="text-lg font-semibold">Recipe item details</h2>
            <p class="mt-1 text-sm text-gray-600">This recipe item has its own inventory and recipe.</p>
            <div class="mt-4 grid gap-4 md:grid-cols-2">
                <x-ui.input name="name" label="Kit name" :value="$kitName" x-model="name" x-on:blur="generateSku()" required />
                <x-ui.input name="sku" label="SKU" value="{{ old('sku', $kit->sku) }}" x-model="sku" x-on:input="editSku()" info="Generated from the name when left blank. You can edit it before saving." />
                <div class="md:col-span-2"><x-ui.media label="Image" name="image_media_name" value="{{ old('image_media_name', $kit->image_media_name) }}" allow_uploads="true" public_usable_only="true" /></div>
                <x-ui.input name="unit" label="Output unit" :value="old('unit', $kit->unit ?: 'kit')" info="For example kit or each. Workshop reservations use whole output units." required />
                <x-ui.select name="status" label="Status">
                    <option value="active" @selected(old('status', $kit->status) === 'active')>Active</option>
                    <option value="archived" @selected(old('status', $kit->status) === 'archived')>Archived</option>
                </x-ui.select>
                <div class="md:col-span-2"><x-ui.input type="textarea" name="notes" label="Notes" rows="3" value="{{ old('notes', $kit->notes) }}" /></div>
            </div>

            <div class="mt-6 border-t border-slate-200 pt-5">
                <div class="flex flex-wrap items-start justify-between gap-3">
                    <div>
                        <h3 class="font-semibold text-gray-900">Stock item recipe</h3>
                        <p class="mt-1 text-sm text-slate-600">Add stock items in the blank row. Quantities and preparation notes are for one kit.</p>
                    </div>
                </div>
                @error('components')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror
                @foreach($errors->getMessages() as $errorKey => $messages)
                    @if(str_starts_with($errorKey, 'components.'))
                        <p class="mt-2 text-sm text-red-700">{{ $messages[0] ?? 'Check this stock item.' }}</p>
                    @endif
                @endforeach
                <x-ui.table variant="plain" table-class="min-w-full border border-gray-200 rounded-md" class="mt-4 overflow-y-visible" caption="Stock item recipe">
                    <thead class="hidden bg-gray-50 text-left text-xs font-semibold uppercase tracking-wide text-gray-500 md:table-header-group">
                        <tr>
                            <th scope="col" class="px-3 py-2">Stock item</th>
                            <th scope="col" class="w-48 px-3 py-2">Quantity per item</th>
                            <th scope="col" class="w-40 px-3 py-2 text-center"><span class="sr-only">Actions</span></th>
                        </tr>
                    </thead>
                    <tbody class="block md:table-row-group">
                        <template x-for="(component, index) in components" :key="index">
                            <tr class="mb-3 block rounded-xl border border-gray-200 bg-white shadow-sm align-top md:mb-0 md:table-row md:rounded-none md:border-0 md:bg-transparent md:shadow-none">
                                <td class="block border-t border-gray-100 px-3 py-3 first:border-t-0 md:table-cell md:border-t md:px-3 md:py-3">
                                    <div class="mb-1 text-[11px] font-semibold uppercase tracking-wide text-gray-500 md:hidden">Stock item</div>
                                    <input type="hidden" x-bind:name="!isBlankComponent(component) ? `components[${index}][stock_item_id]` : null" x-bind:value="component.stock_item_id">
                                    <div class="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-center gap-2 md:flex md:items-start md:gap-3">
                                        <div class="min-w-0 md:flex-1" x-on:stock-item-link-changed="selectComponentStockItem(index); $dispatch('kit-form-dirty')" x-on:input="handleComponentChange(index)" x-on:change="handleComponentChange(index)">
                                            <x-admin.stock-item-link-field model="component" stock-items-expression="stockItems" placeholder="Search name or SKU" aria-label="Stock item in kit" no-matches-text="No matching active stock items." />
                                        </div>
                                        <x-ui.button
                                            type="button"
                                            variant="plain"
                                            class="md:hidden inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-100 p-0! text-slate-600 transition-colors hover:bg-slate-200"
                                            x-on:click="openComponentNote(index)"
                                            x-bind:aria-label="String(component.note || '').trim() ? 'Edit preparation note' : 'Add preparation note'"
                                            x-bind:title="String(component.note || '').trim() ? 'Edit preparation note' : 'Add preparation note'"
                                        >
                                            <i x-bind:class="String(component.note || '').trim() ? 'fa-solid fa-note-sticky' : 'fa-regular fa-note-sticky'" aria-hidden="true"></i>
                                        </x-ui.button>
                                        <x-ui.input-control
                                            class="hidden md:block md:min-w-0 md:flex-1"
                                            type="text"
                                            maxlength="255"
                                            x-bind:name="!isBlankComponent(component) ? `components[${index}][note]` : null"
                                            x-model="component.note"
                                            x-on:input="handleComponentChange(index)"
                                            placeholder="Preparation note"
                                            aria-label="Preparation note"
                                        />
                                    </div>
                                </td>
                                <td class="block border-t border-gray-100 px-3 py-3 md:table-cell md:border-t md:px-3 md:py-3">
                                    <div class="mb-1 text-[11px] font-semibold uppercase tracking-wide text-gray-500 md:hidden">Quantity per item</div>
                                    <x-ui.input-control type="number" min="0.001" step="0.001" x-bind:name="!isBlankComponent(component) ? `components[${index}][quantity]` : null" x-bind:required="!isBlankComponent(component)" x-model="component.quantity" x-on:input="handleComponentChange(index)" x-on:change="handleComponentChange(index)" aria-label="Quantity per item" />
                                </td>
                                <td class="block border-t border-gray-100 px-3 py-3 md:table-cell md:border-t md:px-3 md:py-3">
                                    <div class="mb-1 text-[11px] font-semibold uppercase tracking-wide text-gray-500 md:hidden">Actions</div>
                                    <x-ui.row-actions :menu="false" class="md:justify-end">
                                        <x-ui.row-action label="Move up" icon="fa-solid fa-arrow-up" tone="neutral" type="button" x-on:click="moveComponentUp(index); $dispatch('kit-form-dirty')" x-bind:disabled="index === 0 || isBlankComponent(component)" />
                                        <x-ui.row-action label="Move down" icon="fa-solid fa-arrow-down" tone="neutral" type="button" x-on:click="moveComponentDown(index); $dispatch('kit-form-dirty')" x-bind:disabled="index >= (components.length - 2) || isBlankComponent(component)" />
                                        <x-ui.row-action label="Remove" icon="fa-solid fa-trash" tone="danger" type="button" x-on:click="removeComponent(index); $dispatch('kit-form-dirty')" x-bind:disabled="isBlankComponent(component)" />
                                    </x-ui.row-actions>
                                </td>
                            </tr>
                        </template>
                    </tbody>
                </x-ui.table>
                <dialog x-ref="componentNoteDialog" class="m-auto max-h-[90vh] w-[min(32rem,calc(100%-2rem))] overflow-y-auto rounded-xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-900/50" aria-labelledby="component-note-dialog-title" x-on:cancel.prevent="closeComponentNote()" x-on:close="mobileNoteIndex = null" x-on:click.self="closeComponentNote()">
                    <div class="flex items-start justify-between gap-3 border-b border-slate-200 px-5 py-4">
                        <div class="min-w-0">
                            <h2 id="component-note-dialog-title" class="font-semibold text-slate-900">Preparation note</h2>
                            <p class="mt-1 truncate text-sm text-slate-600" x-text="mobileNoteIndex === null ? 'Recipe item' : (components[mobileNoteIndex]?.item_name || 'Recipe item')"></p>
                        </div>
                        <x-ui.button type="button" variant="plain" class="h-10 w-10 shrink-0 rounded-lg p-0! text-slate-500" x-on:click="closeComponentNote()" aria-label="Close preparation note"><i class="fa-solid fa-xmark" aria-hidden="true"></i></x-ui.button>
                    </div>
                    <div class="space-y-4 px-5 py-4">
                        <div>
                            <label for="mobile-component-note" class="mb-1 block text-sm font-medium text-slate-700">Note for one kit</label>
                            <x-ui.input-control id="mobile-component-note" type="text" maxlength="255" x-model="mobileNoteDraft" x-on:input.stop x-on:keydown.enter.prevent placeholder="For example, cut lengths" />
                        </div>
                        <div class="flex justify-end gap-2">
                            <x-ui.button type="button" color="outline" x-on:click="closeComponentNote()">Cancel</x-ui.button>
                            <x-ui.button type="button" x-on:click="saveComponentNote()">Save note</x-ui.button>
                        </div>
                    </div>
                </dialog>
                <div class="mt-4 flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
                    <div>
                        <span class="block text-sm font-medium text-slate-900">Estimated replacement cost per {{ $kit->unit ?: 'item' }} (ex GST)</span>
                        <span class="mt-0.5 block text-xs text-slate-600">Based on the current replacement costs of recipe items.</span>
                    </div>
                    <span class="font-semibold text-slate-900" x-text="totalCost() === null ? 'Add items and set their costs' : formatAud(totalCost())"></span>
                </div>
            </div>

            <div class="mt-5 flex justify-end"><x-ui.button type="submit">Save kit</x-ui.button></div>
        </form>

        @if($kit->exists)
            @php
                $reserved = (float) ($kit->active_reserved_quantity ?? $kit->activeReservedQuantity());
                $readyMadeAvailable = max(0, (float) $kit->on_hand_quantity - $reserved);
                $reservationShortage = max(0, $reserved - (float) $kit->on_hand_quantity);
                $totalAvailable = $kit->availableQuantity() ?? 0;
                $buildable = max(0, $totalAvailable - $readyMadeAvailable);
            @endphp
            <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                <h2 class="text-lg font-semibold">Ready-made stock</h2>
                <p class="mt-1 text-sm text-slate-600">Ready-made stock is counted separately from additional items that can be assembled from components.</p>
                <div class="mt-4 grid gap-3 sm:grid-cols-3">
                    <div class="rounded-lg bg-slate-50 p-3"><div class="text-xs font-medium uppercase tracking-wide text-slate-500">Ready made, available</div><div class="mt-1 text-lg font-semibold">{{ $kit->formatQuantity($readyMadeAvailable) }}</div></div>
                    <div class="rounded-lg bg-slate-50 p-3"><div class="text-xs font-medium uppercase tracking-wide text-slate-500">Buildable from parts</div><div class="mt-1 text-lg font-semibold">{{ $kit->formatQuantity($buildable) }}</div></div>
                    <div class="rounded-lg bg-slate-50 p-3"><div class="text-xs font-medium uppercase tracking-wide text-slate-500">Total available</div><div class="mt-1 text-lg font-semibold">{{ $kit->formatQuantity($totalAvailable) }}</div></div>
                </div>
                <p class="mt-3 text-xs text-slate-500">{{ $kit->formatQuantity((float) $kit->on_hand_quantity) }} ready-made on hand; {{ $kit->formatQuantity($reserved) }} reserved.</p>
                @if($reservationShortage > 0.0005)
                    <p class="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">
                        Active reservations exceed ready-made stock by {{ $kit->formatQuantity($reservationShortage) }} {{ $kit->unit }}. Review the reservations below or assemble more kits.
                    </p>
                @endif
                @if($activeStockReservations->isNotEmpty())
                    <div class="mt-4 overflow-x-auto">
                        <x-ui.table variant="plain" table-class="min-w-full">
                            <thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500">
                                <tr>
                                    <th class="px-3 py-2">Workshop or order</th>
                                    <th class="px-3 py-2 text-center">Reserved quantity</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100">
                                @foreach($activeStockReservations as $reservationRow)
                                    @php
                                        $reservation = $reservationRow['reservation'];
                                        $reservedWorkshop = $reservationRow['workshop'];
                                    @endphp
                                    <tr>
                                        <td class="px-3 py-2 text-sm">
                                            @if($reservedWorkshop)
                                                <a class="font-medium text-primary-color hover:underline" href="{{ route('admin.workshop.stock-reconciliation', $reservedWorkshop) }}">{{ $reservedWorkshop->title }}</a>
                                                <p class="mt-0.5 text-xs text-gray-500">{{ $reservedWorkshop->starts_at?->format('j M Y, g:i a') ?? 'Date not set' }}</p>
                                            @else
                                                {{ $reservation->purpose ? ucwords(str_replace('_', ' ', (string) $reservation->purpose)) : 'Reservation' }}
                                                <p class="mt-0.5 text-xs text-gray-500">Source {{ $reservation->source_id }}</p>
                                            @endif
                                        </td>
                                        <td class="px-3 py-2 text-center text-sm font-medium tabular-nums">{{ $kit->formatQuantity((float) $reservation->remaining_quantity) }} {{ $kit->unit }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </x-ui.table>
                    </div>
                @endif
                <p x-cloak x-show="kitFormDirty" class="mt-4 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="status">Save the kit details and recipe above before changing stock. Stock actions use the saved recipe.</p>
                <div class="mt-4 grid gap-4 lg:grid-cols-2">
                    <form method="POST" action="{{ route('admin.shop.stock.kit.adjust-ready-made', $kit) }}" class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm" x-on:submit="if (kitFormDirty) $event.preventDefault()">
                        @csrf
                        <h3 class="text-lg font-semibold">Adjust ready-made stock</h3>
                        <p class="mt-1 text-sm text-gray-600">Use a positive quantity to add kits already made or a negative quantity to write them off or correct the count. This does not change component stock.</p>
                        <div class="mt-4 space-y-4">
                            <x-ui.input name="adjustment_quantity" label="Adjustment quantity" type="number" step="1" required />
                            <x-ui.input type="textarea" name="notes" label="Notes" rows="3" />
                        </div>
                        @error('adjustment_quantity')<p class="mt-2 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror
                        <div class="mt-5 flex justify-end"><x-ui.button type="submit" color="outline">Save adjustment</x-ui.button></div>
                    </form>
                    <form x-ref="assemblyPreviewForm" method="GET" action="{{ route('admin.shop.stock.kit.assemble.preview', $kit) }}" class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm" x-on:submit.prevent="openAssemblyDialog($el)">
                        <h3 class="text-lg font-semibold">Assemble kits</h3>
                        <div class="mt-4">
                            <x-ui.input x-ref="assemblyPlannedQuantity" name="quantity" label="Planned kits" type="number" min="1" max="100000" step="1" :value="old('quantity', 1)" />
                        </div>
                        @error('quantity')<p class="mt-2 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror
                        <p x-cloak x-show="assemblyDialogError" x-text="assemblyDialogError" class="mt-3 text-sm text-red-700" role="alert"></p>
                        <div class="mt-5 flex justify-end"><x-ui.button type="submit" x-bind:disabled="kitFormDirty || assemblyDialogLoading" x-text="assemblyDialogLoading ? 'Loading…' : 'Review assembly'">Review assembly</x-ui.button></div>
                    </form>
                </div>
            </section>
        @endif
        @if($kit->exists)
            <div class="flex justify-start border-t border-slate-200 pt-5">
                <x-ui.button type="button" color="danger" x-on:click="$refs.kitDeleteDialog.showModal()">
                    <i class="fa-solid fa-trash mr-2" aria-hidden="true"></i>Delete
                </x-ui.button>
            </div>
        @endif
    </x-container>
    @if($kit->exists)
        <dialog
            x-ref="assemblyDialog"
            class="m-auto max-h-[92vh] w-[min(76rem,calc(100%-1rem))] overflow-y-auto rounded-xl border border-slate-200 bg-white p-3 shadow-2xl backdrop:bg-slate-900/50 sm:p-6"
            aria-labelledby="assembly-dialog-title"
            x-init="$nextTick(() => { if (@js($assemblyPlan !== null)) { $el.showModal(); $nextTick(() => $refs.assemblyDialogContent.querySelector('[data-assembly-quantity]')?.focus()); } })"
            x-on:input="handleAssemblyDialogInput($event)"
            x-on:submit="submitAssemblyDialog($event)"
            x-on:cancel.prevent="closeAssemblyDialog()"
            x-on:click.self="closeAssemblyDialog()"
            x-on:click="if ($event.target.closest('[data-close-assembly-dialog]')) closeAssemblyDialog()"
        >
            <p x-cloak x-show="assemblyDialogLoading" class="mb-3 text-xs text-slate-500" role="status">Updating material quantities…</p>
            <p x-cloak x-show="assemblyDialogError" x-text="assemblyDialogError" class="mb-3 text-sm text-red-700" role="alert"></p>
            <div x-ref="assemblyDialogContent">
                @if($assemblyPlan !== null)
                    @include('admin.shop.stock.kits.assembly-dialog-content', [
                        'kit' => $assemblyPlan['kit'],
                        'plannedQuantity' => $assemblyPlan['quantity'],
                        'completedQuantity' => old('completed_quantity', $assemblyPlan['quantity']),
                        'assemblyRows' => $assemblyPlan['rows'],
                        'dialogMode' => true,
                    ])
                @endif
            </div>
        </dialog>
        <dialog x-ref="kitDeleteDialog" class="m-auto max-h-[90vh] w-[min(34rem,calc(100%-2rem))] overflow-y-auto rounded-xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-900/50" aria-labelledby="kit-delete-title" x-init="$nextTick(() => { if (@js($errors->has('disposition'))) $el.showModal() })" x-on:cancel.prevent="$refs.kitDeleteDialog.close()" x-on:click.self="$refs.kitDeleteDialog.close()">
            <form method="POST" action="{{ route('admin.shop.stock.kit.destroy', $kit) }}">
                @csrf
                @method('DELETE')
                <div class="flex items-start justify-between gap-3 border-b border-slate-200 px-5 py-4">
                    <div class="min-w-0">
                        <h2 id="kit-delete-title" class="text-lg font-semibold text-slate-900">Delete {{ $kit->name }}?</h2>
                        <p class="mt-1 text-sm text-slate-600">{{ $kitDeleteBlockers === [] ? 'This permanently removes the kit and its recipe.' : 'Remove these references before deleting the kit.' }}</p>
                    </div>
                    <x-ui.button type="button" variant="plain" class="h-10 w-10 shrink-0 rounded-lg p-0! text-slate-500" x-on:click="$refs.kitDeleteDialog.close()" aria-label="Close delete kit dialog"><i class="fa-solid fa-xmark" aria-hidden="true"></i></x-ui.button>
                </div>
                <div class="space-y-4 px-5 py-4">
                    @if($kitDeleteBlockers !== [])
                        <ul class="list-disc space-y-1 pl-5 text-sm text-amber-900" role="status">
                            @foreach($kitDeleteBlockers as $blocker)
                                <li>{{ $blocker }}</li>
                            @endforeach
                        </ul>
                    @else
                        @if((float) $kit->on_hand_quantity > 0)
                            <fieldset>
                                <legend class="mb-2 text-sm font-medium text-slate-800">There are {{ $kit->formatQuantity((float) $kit->on_hand_quantity) }} ready-made {{ $kit->unit }}{{ (float) $kit->on_hand_quantity === 1.0 ? '' : 's' }}. Choose what to do with them:</legend>
                                <div class="space-y-2">
                                    <label class="flex cursor-pointer gap-3 rounded-lg border border-slate-200 p-3 hover:bg-slate-50">
                                        <input class="mt-1" type="radio" name="disposition" value="write_off" required @checked(old('disposition') === 'write_off')>
                                        <span><span class="block text-sm font-medium text-slate-900">Write off the ready-made stock</span><span class="mt-0.5 block text-xs text-slate-600">Remove the finished kits from inventory without returning components.</span></span>
                                    </label>
                                    @if($kit->kitComponents->isNotEmpty())
                                        <label class="flex cursor-pointer gap-3 rounded-lg border border-slate-200 p-3 hover:bg-slate-50">
                                            <input class="mt-1" type="radio" name="disposition" value="return_components" required @checked(old('disposition') === 'return_components')>
                                            <span><span class="block text-sm font-medium text-slate-900">Return the recipe components to stock</span><span class="mt-0.5 block text-xs text-slate-600">Add each saved recipe quantity for every ready-made kit back to its stock item.</span></span>
                                        </label>
                                    @endif
                                </div>
                                @error('disposition')<p class="mt-2 text-sm text-rose-700" role="alert">{{ $message }}</p>@enderror
                            </fieldset>
                        @else
                            <p class="text-sm text-slate-700">This kit has no ready-made stock to dispose of.</p>
                        @endif
                        @if(($kit->movements_count ?? 0) > 0)
                            <p class="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">Deleting this kit also removes its kit-specific stock movement history.</p>
                        @endif
                    @endif
                </div>
                <div class="flex flex-col-reverse gap-2 border-t border-slate-200 px-5 py-4 sm:flex-row sm:justify-end">
                    <x-ui.button type="button" color="outline" x-on:click="$refs.kitDeleteDialog.close()">Cancel</x-ui.button>
                    @if($kitDeleteBlockers === [])
                        <x-ui.button type="submit" color="danger">Delete</x-ui.button>
                    @endif
                </div>
            </form>
        </dialog>
    @endif
    </div>
</x-layout>
