<x-layout>
    @php
        $stockItemDeleteBlockers = $stockItemDeleteBlockers ?? [];
        $currentOnHandQuantity = (float) ($stockItem->on_hand_quantity ?? 0);
        $currentReservedQuantity = $stockItem->exists
            ? (float) ($stockItem->active_reserved_quantity ?? $stockItem->activeReservedQuantity())
            : 0;
        $currentAvailableQuantity = $stockItem->exists && $stockItem->tracksInventory()
            ? max(0, $currentOnHandQuantity - $currentReservedQuantity)
            : null;
        $currentReservationShortage = max(0, $currentReservedQuantity - $currentOnHandQuantity);
        $stockItemUnit = trim((string) ($stockItem->unit ?: 'each'));
        $stockItemUnitSuffix = strtolower($stockItemUnit) === 'each' ? '' : ' '.$stockItemUnit;
    @endphp
    <x-mast backRoute="admin.shop.stock.index" backTitle="Stock items" :tabs="$stockTabs">
        {{ $stockItem->exists ? 'Edit' : 'Create' }} stock item
    </x-mast>
    <x-container class="mt-4" inner-class="space-y-6">
        @error('status')<div class="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900" role="alert">{{ $message }}</div>@enderror
        @error('delete')<div class="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900" role="alert">{{ $message }}</div>@enderror
        @php
            $currentReplacementCost = $stockItem->replacementCost();
            $latestReceiptLine = $stockItem->exists ? $stockItem->receiptLines->sortByDesc('id')->first() : null;
            $latestReceiptUnitCost = $latestReceiptLine?->unit_cost_ex_tax;
            $manualReplacementCost = in_array($stockItem->replacement_cost_source, ['manual', 'manual_adjustment'], true)
                ? $stockItem->replacement_unit_cost_ex_tax
                : null;
            $formattedManualReplacementCost = $manualReplacementCost !== null
                ? $stockItem->formatUnitCost((float) $manualReplacementCost)
                : null;
            $initialCostReset = old('replacement_cost_reset') === '1';
            $initialManualReplacementCost = old('replacement_unit_cost_ex_tax', $formattedManualReplacementCost) ?? '';
            $initialDisplayedReplacementCost = $initialCostReset
                ? $latestReceiptUnitCost
                : ($initialManualReplacementCost !== '' ? $initialManualReplacementCost : $currentReplacementCost);
            $initialReplacementCostSource = $initialCostReset || $stockItem->replacement_cost_source === 'latest_receipt'
                ? ($latestReceiptUnitCost !== null ? 'Latest receipt' : 'No cost recorded')
                : ($initialManualReplacementCost !== '' ? 'Manual replacement cost' : ($currentReplacementCost !== null ? 'Calculated replacement cost' : 'No cost recorded'));
        @endphp
        <form
            method="POST"
            action="{{ $stockItem->exists ? route('admin.shop.stock.update', $stockItem) : route('admin.shop.stock.store') }}"
            class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"
            x-data="{
                name: @js(old('name', $stockItem->name)),
                sku: @js(old('sku', $stockItem->sku ?? '')),
                skuTouched: @js(trim((string) old('sku', $stockItem->sku ?? '')) !== ''),
                skuAutoGenerated: @js((bool) old('sku_auto_generated', false)),
                manualReplacementCost: @js($initialCostReset ? '' : (string) $initialManualReplacementCost),
                manualReplacementCostDraft: '',
                replacementCostReset: @js($initialCostReset),
                latestReceiptCost: @js($latestReceiptUnitCost !== null ? (string) $latestReceiptUnitCost : ''),
                displayedReplacementCost: @js($initialDisplayedReplacementCost !== null ? (string) $initialDisplayedReplacementCost : ''),
                replacementCostSource: @js($initialReplacementCostSource),
                manualCostError: '',
                formatReplacementCost(value) {
                    const amount = Number(value);
                    return value === '' || !Number.isFinite(amount) ? 'No cost recorded' : '$' + amount.toFixed(2);
                },
                saveManualReplacementCost(dialog) {
                    const value = String(this.manualReplacementCostDraft || '').trim();
                    const amount = Number(value);
                    if (value === '' || !Number.isFinite(amount) || amount < 0) {
                        this.manualCostError = 'Enter a valid non-negative cost.';
                        return;
                    }

                    this.manualReplacementCost = amount.toFixed(4);
                    this.displayedReplacementCost = this.manualReplacementCost;
                    this.replacementCostReset = false;
                    this.replacementCostSource = 'Manual replacement cost';
                    this.manualCostError = '';
                    dialog.close();
                },
                resetReplacementCost() {
                    this.manualReplacementCost = '';
                    this.displayedReplacementCost = this.latestReceiptCost;
                    this.replacementCostReset = true;
                    this.replacementCostSource = this.latestReceiptCost === '' ? 'No cost recorded' : 'Latest receipt';
                },
                slugify(value) {
                    return String(value || '')
                        .toLowerCase()
                        .normalize('NFD')
                        .replace(/[\u0300-\u036f]/g, '')
                        .replace(/[^a-z0-9]+/g, '-')
                        .replace(/^-+|-+$/g, '')
                        .replace(/-{2,}/g, '-')
                        .slice(0, 120);
                },
                generateSkuFromName() {
                    if (this.skuTouched || String(this.sku || '').trim() !== '') {
                        return;
                    }

                    this.sku = this.slugify(this.name);
                    this.skuAutoGenerated = true;
                },
                handleSkuInput() {
                    this.skuTouched = String(this.sku || '').trim() !== '';
                    this.skuAutoGenerated = false;
                },
            }"
        >
            @csrf
            @if($stockItem->exists) @method('PUT') @endif
            <input type="hidden" name="sku_auto_generated" x-bind:value="skuAutoGenerated ? '1' : '0'">
            <input type="hidden" name="replacement_unit_cost_ex_tax" x-bind:value="manualReplacementCost">
            <input type="hidden" name="replacement_cost_reset" x-bind:value="replacementCostReset ? '1' : '0'">
            <h2 class="text-lg font-semibold">Stock item details</h2>
            <p class="mt-1 text-sm text-gray-600">Use one stock item wherever the same part is sold, included in a kit or used in a workshop. Each receipt keeps its historical cost. The latest unit cost is used for current cost calculations.</p>
            <div class="mt-4 grid gap-4 md:grid-cols-2">
                <x-ui.input name="name" label="Name" value="{{ old('name', $stockItem->name) }}" x-model="name" x-on:blur="generateSkuFromName()" required />
                <x-ui.input name="sku" label="SKU" value="{{ old('sku', $stockItem->sku) }}" x-model="sku" x-on:input="handleSkuInput()" info="Generated from the name when left blank. You can edit it before saving." />
                <div class="md:col-span-2">
                    <x-ui.media label="Image" name="image_media_name" value="{{ old('image_media_name', $stockItem->image_media_name) }}" allow_uploads="true" public_usable_only="true" />
                </div>
                <x-ui.input name="unit" label="Unit" value="{{ old('unit', $stockItem->unit ?: 'each') }}" info="For example each, metre, set, or gram." required />
                <x-ui.select name="status" label="Status">
                    <option value="active" @selected(old('status', $stockItem->status) === 'active')>Active</option>
                    <option value="archived" @selected(old('status', $stockItem->status) === 'archived')>Archived</option>
                </x-ui.select>
                @if($stockItem->stock_item_group_id)
                    <input type="hidden" name="stock_item_group_id" value="{{ old('stock_item_group_id', $stockItem->stock_item_group_id) }}">
                    <input type="hidden" name="variant_name" value="{{ old('variant_name', $stockItem->variant_name) }}">
                @endif
                <div>
                    <p class="mb-1 pl-1 text-sm">Replacement cost</p>
                    <div class="flex min-h-[42px] items-center justify-between gap-3 rounded-lg border border-slate-300 bg-slate-50 px-3 py-1.5 lg:h-[42px]">
                        <div class="min-w-0 flex-1">
                            <p class="flex min-w-0 flex-wrap items-baseline gap-x-2">
                                <strong class="font-bold tabular-nums text-slate-900" x-bind:class="displayedReplacementCost === '' ? 'text-sm' : 'text-lg'" x-text="formatReplacementCost(displayedReplacementCost)">{{ $initialDisplayedReplacementCost !== null ? '$'.number_format((float) $initialDisplayedReplacementCost, 2, '.', ',') : 'No cost recorded' }}</strong>
                                <span class="text-xs text-slate-600">per {{ $stockItem->unit }} · ex GST</span>
                                <span class="text-xs text-slate-500" x-show="replacementCostSource !== 'No cost recorded'" x-text="replacementCostSource"></span>
                            </p>
                        </div>
                        <div class="flex shrink-0 items-center gap-1">
                            <x-ui.button type="button" variant="plain" class="size-9 rounded-lg p-0! text-slate-600 hover:bg-white" data-open-dialog="stock-replacement-cost-dialog" x-on:click="manualReplacementCostDraft = manualReplacementCost; manualCostError = ''" title="Set a manual replacement cost" aria-label="Set a manual replacement cost">
                                <i class="fa-solid fa-pen" aria-hidden="true"></i>
                            </x-ui.button>
                            @if($latestReceiptUnitCost !== null)
                                <x-ui.button type="button" variant="plain" class="size-9 rounded-lg p-0! text-slate-600 hover:bg-white disabled:cursor-not-allowed disabled:opacity-40" x-bind:disabled="manualReplacementCost === '' || replacementCostReset" x-on:click="resetReplacementCost()" title="Use latest receipt cost" aria-label="Reset to latest receipt cost">
                                    <i class="fa-solid fa-rotate-left" aria-hidden="true"></i>
                                </x-ui.button>
                            @endif
                        </div>
                    </div>
                    @error('replacement_unit_cost_ex_tax')<p class="mt-1 text-xs text-red-600" role="alert">{{ $message }}</p>@enderror
                </div>
                <x-ui.input name="reorder_point" label="Reorder alert threshold" type="number" min="0" step="0.001" value="{{ old('reorder_point', $stockItem->formatQuantity((float) ($stockItem->reorder_point ?? 0))) }}" info="Set to 0 to turn this off. An alert appears when available stock falls below this quantity." />
                <div class="md:col-span-2">
                    <x-ui.checkbox
                        name="shared_workshop_supply"
                        value="1"
                        label="Share this supply between workshops"
                        :checked="old('shared_workshop_supply', $stockItem->shared_workshop_supply ?? false)"
                        info="Shared reserve includes a compounded 10% buffer."
                        class="mb-0"
                    />
                </div>
                @if(! $stockItem->exists)
                    <x-ui.input name="opening_quantity" label="Opening quantity" type="number" min="0" step="0.001" value="{{ old('opening_quantity', 0) }}" />
                @endif
                <div class="md:col-span-2"><x-ui.input type="textarea" name="notes" label="Notes" rows="3" value="{{ old('notes', $stockItem->notes) }}" /></div>
            </div>
            <div class="mt-5 flex justify-end"><x-ui.button type="submit">Save stock item</x-ui.button></div>
            <x-ui.list-dialog id="stock-replacement-cost-dialog" title="Manual replacement cost" kind="edit" centered>
                <div class="space-y-3 px-5 py-4">
                    <p class="text-sm text-slate-600">Set a manual AUD cost excluding GST. Reset it to use the latest receipt cost.</p>
                    <label class="block text-sm" for="manual-replacement-cost-entry">Manual cost (AUD, ex GST)</label>
                    <x-ui.input-control id="manual-replacement-cost-entry" type="text" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,4})?" placeholder="0.00" x-model="manualReplacementCostDraft" x-on:input="manualCostError = ''" />
                    <p x-cloak x-show="manualCostError" class="text-sm text-red-700" role="alert" x-text="manualCostError"></p>
                </div>
                <div class="sm-dialog-footer">
                    <x-ui.button type="button" color="outline" data-close-dialog>Cancel</x-ui.button>
                    <x-ui.button type="button" x-on:click="saveManualReplacementCost($el.closest('dialog'))">Save cost</x-ui.button>
                </div>
            </x-ui.list-dialog>
        </form>

        @if($stockItem->exists)
            @php
                $stockMovementScope = 'stock-item-'.$stockItem->id;
                $initialMovementDate = old('date', now()->toDateString());
                $initialMovementCost = old('total_cost_ex_tax', '');
                $initialMovementExpenseId = old('expense_id', '');
            @endphp
            <form
                method="POST"
                x-data="SM.stockReceiptMovementForm(@js($initialMovementDate), @js($initialMovementCost), @js($initialMovementExpenseId), @js($stockMovementScope))"
                x-on:stock-expense-selected.window="selectExpense($event.detail.expense, $event.detail.scope)"
                x-bind:action="isReceipt ? @js(route('admin.shop.stock.receive', $stockItem)) : @js(route('admin.shop.stock.adjust', $stockItem))"
                x-on:submit="formatTotalCost($el.querySelector('[name=total_cost_ex_tax]'))"
                class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"
            >
                @csrf
                <div class="flex flex-wrap items-start justify-between gap-3">
                    <div>
                        <h2 class="text-lg font-semibold">Stock movement</h2>
                        <p class="mt-1 text-sm text-gray-600" x-cloak x-show="isReceipt">Record a purchase with its total cost excluding GST, including freight.</p>
                        <p class="mt-1 text-sm text-gray-600" x-cloak x-show="!isReceipt">Leave cost and expense blank to record an adjustment. Use a minus quantity to write off stock.</p>
                    </div>
                    <div class="min-w-40 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-right">
                        <p class="mt-0.5 text-lg font-semibold text-slate-900">
                            @if($currentAvailableQuantity !== null)
                                {{ $stockItem->formatQuantity($currentAvailableQuantity) }}{{ $stockItemUnitSuffix }} available
                            @else
                                Not tracked
                            @endif
                        </p>
                        <p class="mt-0.5 text-xs text-slate-500">{{ $stockItem->formatQuantity($currentOnHandQuantity) }} on hand · {{ $stockItem->formatQuantity($currentReservedQuantity) }} reserved{{ $stockItem->shared_workshop_supply ? ' (forecast)' : '' }}</p>
                    </div>
                </div>
                <div class="mt-4 grid items-start gap-4 sm:grid-cols-2">
                    <div>
                        <x-ui.input name="quantity" label="Quantity" type="number" step="0.001" x-bind:min="isReceipt ? '0.001' : null" x-on:wheel.prevent="$el.blur()" required />
                    </div>
                    <div>
                        <x-ui.input name="total_cost_ex_tax" label="Total cost (AUD, ex GST)" type="text" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" min="0" x-model="totalCost" x-on:input="manualTotalCost()" x-on:blur="formatTotalCost()" x-bind:required="expenseId !== ''" />
                    </div>
                    <div>
                        <x-ui.input name="date" label="Date" type="date" x-model="movementDate" required />
                    </div>
                    <div class="sm:col-span-2">
                        <x-admin.stock-receipt-expense-field :expenses="$receiptExpenses" :scope="$stockMovementScope" />
                    </div>
                    <div class="sm:col-span-2">
                        <x-ui.input type="textarea" name="notes" label="Notes" rows="2" />
                    </div>
                </div>
                <div class="mt-5 flex justify-end">
                    <x-ui.button type="submit"><span x-text="isReceipt ? 'Receive stock' : 'Save adjustment'"></span></x-ui.button>
                </div>
            </form>

            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                <h2 class="text-lg font-semibold">Current links</h2>
                <div class="mt-3 grid gap-4 text-sm md:grid-cols-2">
                    <div><h3 class="font-semibold">Products</h3><ul class="mt-1 list-disc pl-5 text-gray-600">@forelse($stockItem->products as $product)<li><a class="text-primary-color hover:underline" href="{{ route('admin.shop.product.edit', $product) }}">{{ $product->title }}</a></li>@empty<li>No direct product links.</li>@endforelse</ul></div>
                    <div><h3 class="font-semibold">Used in kits</h3><ul class="mt-1 list-disc pl-5 text-gray-600">@forelse($stockItem->usedInKits as $component)<li><a class="text-primary-color hover:underline" href="{{ route('admin.shop.stock.kit.edit', $component->kit) }}">{{ $component->kit?->linkLabel() ?? 'Kit' }}</a> · {{ $stockItem->formatQuantity((float) $component->quantity) }} {{ $stockItem->unit }} per kit</li>@empty<li>Not used in any kits.</li>@endforelse</ul></div>
                    <div><h3 class="font-semibold">Pick list materials</h3><ul class="mt-1 list-disc pl-5 text-gray-600">@forelse($stockItem->pickListItems as $item)<li>{{ $item->template?->name ?? 'Blueprint' }} · {{ $item->stockItem?->linkLabel() ?? $item->item_name }}</li>@empty<li>No workshop blueprint links.</li>@endforelse</ul></div>
                </div>
            </div>

            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm" id="stock-reservations">
                <div class="flex flex-wrap items-start justify-between gap-3">
                    <div>
                        <h2 class="text-lg font-semibold">Reserved stock</h2>
                        <p class="mt-1 text-sm text-gray-600">
                            Current reservations are listed below. Reserved quantities are included in on-hand stock.
                            @if($stockItem->shared_workshop_supply) Each workshop keeps its planned pack quantity while the total reserve uses the compounded 10% forecast. @endif
                        </p>
                    </div>
                    <p class="rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium tabular-nums text-slate-700">
                        {{ $stockItem->formatQuantity($currentOnHandQuantity) }} on hand ·
                        {{ $stockItem->formatQuantity($currentReservedQuantity) }} reserved{{ $stockItem->shared_workshop_supply ? ' (forecast)' : '' }} ·
                        {{ $currentAvailableQuantity !== null ? $stockItem->formatQuantity($currentAvailableQuantity).$stockItemUnitSuffix : '—' }} available
                    </p>
                </div>
                @if($currentReservationShortage > 0.0005)
                    <p class="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">
                        Active reservations exceed stock on hand by {{ $stockItem->formatQuantity($currentReservationShortage) }}{{ $stockItemUnitSuffix }}. Review the reservations below or receive more stock.
                    </p>
                @endif
                @if($activeStockReservations->isNotEmpty())
                    <div class="mt-4 overflow-x-auto">
                        <x-ui.table variant="plain" table-class="min-w-full">
                            <thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500">
                                <tr>
                                    <th class="px-3 py-2">Workshop</th>
                                    <th class="px-3 py-2 text-center">{{ $stockItem->shared_workshop_supply ? 'Planned to pack' : 'Currently reserved' }}</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100">
                                @foreach($activeStockReservations as $reservationRow)
                                    @php
                                        $reservation = $reservationRow['reservation'];
                                        $reservedWorkshop = $reservationRow['workshop'];
                                    @endphp
                                    <tr>
                                        <td class="px-3 py-2 text-sm">
                                            @if($reservedWorkshop)
                                                <a class="font-medium text-primary-color hover:underline" href="{{ route('admin.workshop.stock-reconciliation', $reservedWorkshop) }}">{{ $reservedWorkshop->title }}</a>
                                                <p class="mt-0.5 text-xs text-gray-500">{{ $reservedWorkshop->starts_at?->format('j M Y, g:i a') ?? 'Date not set' }}</p>
                                            @else
                                                {{ $reservation->purpose ? ucwords(str_replace('_', ' ', (string) $reservation->purpose)) : 'Reservation' }}
                                                <p class="mt-0.5 text-xs text-gray-500">Source {{ $reservation->source_id }}</p>
                                            @endif
                                        </td>
                                        <td class="px-3 py-2 text-center text-sm font-medium tabular-nums">{{ $stockItem->formatQuantity((float) $reservation->remaining_quantity) }}{{ $stockItemUnitSuffix }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </x-ui.table>
                    </div>
                @else
                    <p class="mt-4 rounded-lg border border-gray-200 bg-gray-50 px-3 py-2 text-sm text-gray-600">No active reservations.</p>
                @endif
            </div>

            @php
                $recentStockMovements = $stockItem->movements->sortByDesc('occurred_at')->take(20);
            @endphp
            <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                <h2 class="text-lg font-semibold">Recent stock history</h2>
                @if($errors->has('receipt'))
                    <p class="mt-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">{{ $errors->first('receipt') }}</p>
                @endif
                <div class="mt-3 overflow-x-auto">
                    <x-ui.table variant="plain" table-class="min-w-full">
                        <thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500">
                            <tr>
                                <th class="px-3 py-2">When</th>
                                <th class="px-3 py-2 text-center">Type</th>
                                <th class="px-3 py-2 text-center">Quantity</th>
                                <th class="px-3 py-2 text-center">Total cost (ex GST)</th>
                                <th class="px-3 py-2 text-center">Unit cost</th>
                                <th class="px-3 py-2">Notes</th>
                                <th class="px-3 py-2 text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-100">
                            @forelse($recentStockMovements as $movement)
                                @php
                                    $receiptLine = $movement->receiptLine;
                                @endphp
                                <tr>
                                    <td class="px-3 py-2 text-sm">{{ $movement->occurred_at?->format('j M Y') }}</td>
                                    <td class="px-3 py-2 text-center text-sm">{{ ucfirst($movement->movement_type) }}</td>
                                    <td class="px-3 py-2 text-center text-sm tabular-nums {{ (float) $movement->quantity < 0 ? 'text-red-700' : 'text-green-700' }}">{{ $stockItem->formatQuantity((float) $movement->quantity) }}</td>
                                    <td class="px-3 py-2 text-center text-sm tabular-nums">{{ $receiptLine ? '$'.number_format((float) $receiptLine->total_cost_ex_tax, 2, '.', ',') : '—' }}</td>
                                    <td class="px-3 py-2 text-center text-sm tabular-nums">{{ $movement->unit_cost_ex_tax !== null ? '$'.number_format((float) $movement->unit_cost_ex_tax, 2, '.', ',') : '—' }}</td>
                                    <td class="px-3 py-2 text-sm text-gray-600">{{ $receiptLine ? ($receiptLine->receipt?->notes ?: '—') : ($movement->notes ?: '—') }}</td>
                                    <td class="px-3 py-2 text-center">
                                        @if($receiptLine)
                                            <x-ui.action-menu :id="'stock-receipt-actions-'.$receiptLine->id" title="Actions">
                                                <x-ui.row-action type="button" :data-open-dialog="'stock-receipt-edit-'.$receiptLine->id" label="Edit" icon="fa-solid fa-pen" tone="neutral" />
                                                <x-ui.row-action type="button" :data-open-dialog="'stock-receipt-delete-'.$receiptLine->id" label="Delete" icon="fa-solid fa-trash" tone="danger" />
                                            </x-ui.action-menu>
                                        @elseif($movement->movement_type === \App\Models\StockMovement::TYPE_ADJUSTMENT && $movement->stock_receipt_line_id === null && $movement->source_type === null && $movement->source_id === null)
                                            <x-ui.action-menu :id="'stock-adjustment-actions-'.$movement->id" title="Actions">
                                                <x-ui.row-action type="button" :data-open-dialog="'stock-adjustment-edit-'.$movement->id" label="Edit" icon="fa-solid fa-pen" tone="neutral" />
                                            </x-ui.action-menu>
                                        @else
                                            <span class="text-sm text-gray-400">—</span>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr><td colspan="7" class="px-3 py-4 text-sm text-gray-500">No movements yet.</td></tr>
                            @endforelse
                        </tbody>
                    </x-ui.table>
                </div>
            </div>

            @foreach($recentStockMovements as $movement)
                @php
                    $receiptLine = $movement->receiptLine;
                    $receipt = $receiptLine?->receipt;
                @endphp
                @continue(! $receiptLine || ! $receipt)

                @php
                    $fieldPrefix = 'receipt_'.$receiptLine->id.'_';
                    $editDialogId = 'stock-receipt-edit-'.$receiptLine->id;
                    $deleteDialogId = 'stock-receipt-delete-'.$receiptLine->id;
                    $supplierName = $receipt->supplier?->name ?: $receipt->supplier?->supplier ?: '';
                    $initialReceiptDate = old($fieldPrefix.'received_at', $receipt->received_at?->toDateString() ?? '');
                    $initialReceiptCost = old($fieldPrefix.'total_cost_ex_tax', number_format((float) $receiptLine->total_cost_ex_tax, 2, '.', ''));
                    $isEditError = old('stock_receipt_action') === 'edit' && (int) old('stock_receipt_line_id') === (int) $receiptLine->id;
                    $isDeleteError = old('stock_receipt_action') === 'delete' && (int) old('stock_receipt_line_id') === (int) $receiptLine->id;
                @endphp

                <x-ui.list-dialog :id="$editDialogId" :title="'Edit stock receipt · '.$stockItem->name" kind="edit" centered>
                    <form method="POST" action="{{ route('admin.shop.stock.receipt.update', [$stockItem, $receiptLine]) }}" x-data="SM.stockReceiptMovementForm(@js($initialReceiptDate), @js($initialReceiptCost), @js($receipt->expense_id ?? ''), @js('receipt-'.$receiptLine->id))" x-on:stock-expense-selected.window="selectExpense($event.detail.expense, $event.detail.scope)">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="stock_receipt_line_id" value="{{ $receiptLine->id }}">
                        <input type="hidden" name="stock_receipt_action" value="edit">
                        <div class="px-5 py-4">
                            <p class="text-sm text-slate-600">Enter the total cost excluding GST. The per-unit cost is calculated from the quantity.</p>
                            @if($isEditError)
                                @foreach([$fieldPrefix.'quantity', $fieldPrefix.'total_cost_ex_tax', 'receipt'] as $errorKey)
                                    @if($errors->has($errorKey))
                                        <p class="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">{{ $errors->first($errorKey) }}</p>
                                    @endif
                                @endforeach
                            @endif
                            <div class="mt-4 grid items-start gap-x-4 gap-y-2 sm:grid-cols-2">
                                <x-ui.input class="mb-0" :name="$fieldPrefix.'quantity'" label="Quantity" type="number" min="0.001" step="0.001" :value="$receiptLine->quantity" required />
                                <x-ui.input class="mb-0" :name="$fieldPrefix.'total_cost_ex_tax'" label="Total cost (AUD, ex GST)" type="text" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" :value="$initialReceiptCost" x-model="totalCost" x-on:input="manualTotalCost()" x-on:blur="if ($el.value !== '' && Number.isFinite(Number($el.value))) { $el.value = Number($el.value).toFixed(2); totalCost = $el.value }" />
                                <x-ui.input class="mb-0" :name="$fieldPrefix.'received_at'" label="Date received" type="date" :value="$initialReceiptDate" x-model="movementDate" required />
                                <div class="sm:col-span-2">
                                    <x-admin.stock-receipt-expense-field
                                        :expenses="$receiptExpenses"
                                        :supplier="$supplierName"
                                        :expense-id="$receipt->expense_id ?? ''"
                                        :field-prefix="$fieldPrefix"
                                        :scope="'receipt-'.$receiptLine->id"
                                    />
                                </div>
                                <div class="sm:col-span-2"><x-ui.input class="mb-0" type="textarea" :name="$fieldPrefix.'notes'" label="Notes" rows="2" :value="$receipt->notes" /></div>
                            </div>
                        </div>
                        <div class="sm-dialog-footer">
                            <x-ui.button type="button" color="outline" data-close-dialog>Cancel</x-ui.button>
                            <x-ui.button type="submit">Save receipt</x-ui.button>
                        </div>
                    </form>
                </x-ui.list-dialog>

                <x-ui.list-dialog :id="$deleteDialogId" :title="'Delete stock receipt · '.$stockItem->name" kind="edit">
                    <form method="POST" action="{{ route('admin.shop.stock.receipt.delete', [$stockItem, $receiptLine]) }}">
                        @csrf
                        @method('DELETE')
                        <input type="hidden" name="stock_receipt_line_id" value="{{ $receiptLine->id }}">
                        <input type="hidden" name="stock_receipt_action" value="delete">
                        <div class="space-y-3 px-5 py-4">
                            <p class="text-sm text-slate-700">Delete this receipt of {{ $stockItem->formatQuantity((float) $receiptLine->quantity) }} {{ $stockItem->unit }} for ${{ number_format((float) $receiptLine->total_cost_ex_tax, 2, '.', ',') }} ex GST?</p>
                            <p class="text-sm text-slate-500">The received quantity will be removed from on-hand stock. A receipt cannot be deleted if its removal would take stock below zero or below current reservations.</p>
                            @if($isDeleteError && $errors->has('receipt'))
                                <p class="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">{{ $errors->first('receipt') }}</p>
                            @endif
                        </div>
                        <div class="sm-dialog-footer">
                            <x-ui.button type="button" color="outline" data-close-dialog>Cancel</x-ui.button>
                            <x-ui.button type="submit" color="danger">Delete receipt</x-ui.button>
                        </div>
                    </form>
                </x-ui.list-dialog>

                @if($errors->any() && $isEditError)
                    @push('scripts')
                        <script nonce="{{ \Illuminate\Support\Facades\Vite::cspNonce() }}">
                            document.addEventListener('DOMContentLoaded', () => document.getElementById(@js($editDialogId))?.showModal());
                        </script>
                    @endpush
                @elseif($errors->any() && $isDeleteError)
                    @push('scripts')
                        <script nonce="{{ \Illuminate\Support\Facades\Vite::cspNonce() }}">
                            document.addEventListener('DOMContentLoaded', () => document.getElementById(@js($deleteDialogId))?.showModal());
                        </script>
                    @endpush
                @endif
            @endforeach

            @foreach($recentStockMovements as $movement)
                @continue($movement->movement_type !== \App\Models\StockMovement::TYPE_ADJUSTMENT || $movement->stock_receipt_line_id !== null || $movement->source_type !== null || $movement->source_id !== null)

                @php
                    $editDialogId = 'stock-adjustment-edit-'.$movement->id;
                    $fieldPrefix = 'adjustment_'.$movement->id.'_';
                    $isEditError = old('stock_adjustment_action') === 'edit'
                        && (int) old('stock_adjustment_movement_id') === (int) $movement->id;
                @endphp

                <x-ui.list-dialog :id="$editDialogId" title="Edit stock adjustment" kind="edit" centered>
                    <form method="POST" action="{{ route('admin.shop.stock.adjustment.update', [$stockItem, $movement]) }}">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="stock_adjustment_movement_id" value="{{ $movement->id }}">
                        <input type="hidden" name="stock_adjustment_action" value="edit">
                        <div class="px-5 py-4">
                            <p class="text-sm text-slate-600">Use a positive quantity to add stock or a negative quantity to remove it.</p>
                            @if($isEditError)
                                @foreach([$fieldPrefix.'quantity', 'stock_adjustment'] as $errorKey)
                                    @if($errors->has($errorKey))
                                        <p class="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900" role="alert">{{ $errors->first($errorKey) }}</p>
                                    @endif
                                @endforeach
                            @endif
                            <div class="mt-4 grid items-start gap-x-4 gap-y-2 sm:grid-cols-2">
                                <x-ui.input class="mb-0" :name="$fieldPrefix.'quantity'" label="Adjustment quantity" type="number" step="0.001" :value="number_format((float) $movement->quantity, 3, '.', '')" x-on:wheel.prevent="$el.blur()" required />
                                <div class="sm:col-span-2"><x-ui.input class="mb-0" type="textarea" :name="$fieldPrefix.'notes'" label="Notes" rows="2" :value="$movement->notes" /></div>
                            </div>
                        </div>
                        <div class="sm-dialog-footer">
                            <x-ui.button type="button" color="outline" data-close-dialog>Cancel</x-ui.button>
                            <x-ui.button type="submit">Save adjustment</x-ui.button>
                        </div>
                    </form>
                </x-ui.list-dialog>

                @if($errors->any() && $isEditError)
                    @push('scripts')
                        <script nonce="{{ \Illuminate\Support\Facades\Vite::cspNonce() }}">
                            document.addEventListener('DOMContentLoaded', () => document.getElementById(@js($editDialogId))?.showModal());
                        </script>
                    @endpush
                @endif
            @endforeach
            <div class="flex justify-start border-t border-slate-200 pt-5">
                <x-ui.button type="button" color="danger" data-open-dialog="stock-item-delete-dialog">
                    <i class="fa-solid fa-trash mr-2" aria-hidden="true"></i>Delete
                </x-ui.button>
            </div>
        @endif
    </x-container>
    @if($stockItem->exists)
        <x-ui.list-dialog id="stock-item-delete-dialog" title="Delete" kind="edit" centered>
            <form method="POST" action="{{ route('admin.shop.stock.destroy', $stockItem) }}">
                @csrf
                @method('DELETE')
                <div class="space-y-3 px-5 py-4">
                    <p class="text-sm text-slate-700">Permanently delete <strong>{{ $stockItem->linkLabel() }}</strong>?</p>
                    @if($stockItemDeleteBlockers !== [])
                        <div class="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900">
                            <p class="font-medium">This item cannot be deleted yet:</p>
                            <ul class="mt-1 list-disc space-y-1 pl-5">
                                @foreach($stockItemDeleteBlockers as $blocker)<li>{{ $blocker }}</li>@endforeach
                            </ul>
                        </div>
                        <p class="text-sm text-slate-600">Archive it when it is no longer in use to preserve its stock history.</p>
                    @else
                        <p class="text-sm text-slate-600">This is permanent and cannot be undone.</p>
                    @endif
                </div>
                <div class="sm-dialog-footer">
                    <x-ui.button type="button" color="outline" data-close-dialog>Cancel</x-ui.button>
                    @if($stockItemDeleteBlockers === [])<x-ui.button type="submit" color="danger">Delete</x-ui.button>@endif
                </div>
            </form>
        </x-ui.list-dialog>
    @endif
</x-layout>
