<x-finance.panel title="Monthly GST">
    <form method="GET" action="{{ route('admin.cost-centre.gst') }}" class="mb-4 flex items-end gap-3"><x-ui.input name="month" label="Month" type="month" :value="$month->format('Y-m')" class="mb-0" /><x-ui.button type="submit">Show</x-ui.button></form>
    <div class="grid gap-4 sm:grid-cols-3">@foreach(['GST on sales' => $gst['sales'], 'Recorded purchase credits' => $gst['credits'], 'Net GST' => $gst['net']] as $label => $amount)<div class="rounded-xl bg-slate-50 p-4"><p>{{ $label }}</p><p class="text-2xl font-semibold">{{ money($amount / 100) }}</p></div>@endforeach</div>
    <p class="mt-4 text-sm text-slate-600">Uses received payments and paid expenses. Pending bank transfers, unsuccessful gateway payments and non-cash entries are excluded. Purchase GST must represent eligible credits. This tracks the GST portion only; other BAS obligations need their own reserves.</p>
</x-finance.panel>
<x-finance.panel title="Record a GST settlement">
    <p class="mb-4 text-sm text-slate-600">Enter the GST component paid to the ATO. Use a negative amount for a GST refund. Historical payments before the opening date are retained for reference and do not reduce current cash again.</p>
    <form method="POST" action="{{ route('admin.finance.settlement') }}">@csrf<div class="grid gap-x-4 sm:grid-cols-2"><x-ui.input name="period" label="BAS month" type="month" :value="$month->format('Y-m')" required /><x-ui.input name="paid_on" label="Payment / refund date" type="date" :value="now()->toDateString()" required /><x-ui.input name="amount" label="GST settled (negative for refund)" type="number" step="0.01" required /><x-ui.input name="reference" label="Payment reference" required /></div><x-finance.save>Record settlement</x-finance.save></form>
</x-finance.panel>
<x-finance.panel title="GST settlements"><x-ui.table variant="listing"><thead><tr><th class="text-center">BAS month</th><th class="text-center">Paid / received</th><th class="text-center">GST settled</th><th>Reference</th></tr></thead><tbody>@forelse($settlements as $settlement)<tr><td class="text-center whitespace-nowrap">{{ substr($settlement->period, 0, 7) }}</td><td class="text-center whitespace-nowrap">{{ $settlement->paid_on }}</td><td class="text-center whitespace-nowrap">{{ money($settlement->cents / 100) }}</td><td>{{ $settlement->reference }}</td></tr>@empty<tr><td colspan="4">No settlements recorded.</td></tr>@endforelse</tbody></x-ui.table><x-ui.list-pagination :paginator="$settlements" label="settlements" /></x-finance.panel>
