name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:43.78.0
    steps:
      - uses: actions/checkout@v5

      - run: renovate
        working-directory: ${{ github.workspace }}
        env:
          RENOVATE_CONFIG_FILE: "renovate-config.json"
          LOG_LEVEL: "info"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
