name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: renovatebot/github-action@v43.78.0
        env:
          RENOVATE_CONFIG_FILE: renovate-config.json
          LOG_LEVEL: info
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
